import {createHash,randomUUID} from 'node:crypto';
import {z} from 'zod';
import {subjects,timetableSlotSchema,canAccessOwned,canTeach, normalizeSlotTargets } from './teacherWorkspacePolicy.js';
import {normalizeNotionPageId as uuid} from './notionPageId.js';
import {coreActive} from './academyCore.js';
import {DIRECTORY_ROWS,DIRECTORY_HISTORY,directoryRowKey} from './academyDirectorySource.js';
const hash=(v:any)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
export const MANAGED_STATE='academyManagedMigration',MANAGED_LINKS='academyManagedSources',MANAGED_HISTORY='academyManagedHistory',CLASS_AUTHORITY='academyClassAuthority';
type Kind='classes'|'curricula';
const collection=(kind:Kind)=>kind==='classes'?'teacherClasses':'teacherCurricula';
export async function classesActive(db:any,actor:any){return actor.academyId==='main'&&Boolean((await db.collection(CLASS_AUTHORITY).doc('main').get()).data()?.active);}
const classSchema=z.object({name:z.string().min(1).max(200),status:z.enum(['대기','진행 중','중단']).optional(),subject:z.enum(subjects),students:z.array(z.string().uuid()).max(100),slots:z.array(timetableSlotSchema.and(z.object({id:z.string().uuid().optional(),notionEditedAt:z.string().optional(),status:z.enum(['대기','진행 중','중단']).optional()}))).max(14),books:z.array(z.object({id:z.string().uuid().optional(),linkedPlanId:z.string().uuid().optional(),progress:z.string().max(100).optional(),notionEditedAt:z.string().optional(),title:z.string().trim().min(1).max(300),status:z.enum(['past','current','planned'])})).max(100).optional()});
const planSchema=z.object({title:z.string().min(1).max(200),subject:z.enum(subjects),content:z.string().max(30000),classId:z.string().uuid().nullable().optional()});
export async function readManaged(db:any,actor:any){const out:any={classes:[],curricula:[],issues:[],sources:[]};const kinds=['classes','curricula'] as Kind[];const results=await Promise.all(kinds.map(kind=>db.collection(collection(kind)).where('academyId','==',actor.academyId).limit(501).get()));for(const [i,kind] of kinds.entries()){const q=results[i];if(q.docs.length>500)throw Error('CORE_CUTOVER_LIMIT');out[kind]=q.docs.map((d:any)=>({id:d.id,...d.data()})).filter((r:any)=>!r.archived&&(canAccessOwned(actor,r.ownerUid,r.academyId)||(r.assignedUids||[]).includes(actor.uid)));}return out;}
export async function saveManaged(db:any,actor:any,kind:Kind,input:any){
 if(!await coreActive(db,actor))throw Error('CORE_NOT_READY');
 const value=kind==='classes'?classSchema.parse(input.data):planSchema.parse(input.data),id=input.id?z.string().uuid().parse(input.id):randomUUID(),ref=db.collection(collection(kind)).doc(id);
 return db.runTransaction(async(tx:any)=>{
  if(!(await tx.get(db.collection(CLASS_AUTHORITY).doc('main'))).data()?.active)throw Error('CORE_NOT_READY');const old=(await tx.get(ref)).data();if(old?.archived||old&&!canAccessOwned(actor,old.ownerUid,old.academyId))throw Error('FORBIDDEN');if(old&&(input.revision??0)!==old.revision)throw Error('DRAFT_CONFLICT');if(old?.notionPageId&&old.subject!==value.subject)throw Error('SOURCE_IDENTITY_LOCKED');
  let prepared:any={...value};const studentChanges=[];
  if(kind==='classes'){
   const v:any=value;if(new Set(v.students).size!==v.students.length)throw Error('INVALID_INPUT');if(v.students.some((key:string)=>!canTeach(actor,key,v.subject)))throw Error('FORBIDDEN');
   const books=[];for(const b of v.books||[]){if(b.linkedPlanId){const linked=(await tx.get(db.collection('teacherCurricula').doc(b.linkedPlanId))).data();if(!linked||linked.archived||linked.academyId!==actor.academyId||linked.subject!==v.subject||!linked.isCommon)throw Error('FORBIDDEN');books.push({...b,id:b.linkedPlanId,title:linked.title});}else books.push({...b,id:b.id||randomUUID()});}if(new Set(books.map(b=>b.id)).size!==books.length)throw Error('INVALID_INPUT');
   const status=v.status||old?.status||'진행 중',slots=v.slots.map((s:any)=>normalizeSlotTargets({...s,id:s.id||randomUUID(),status:status==='중단'?'중단':s.status||'진행 중'},v.students||[]));if(new Set(slots.map((s:any)=>s.id)).size!==slots.length)throw Error('INVALID_INPUT');prepared={...v,status,slots,books};
   for(const key of [...new Set<string>([...(old?.students||[]),...v.students])]){const sr=db.collection(DIRECTORY_ROWS).doc(directoryRowKey('students',key)),s=(await tx.get(sr)).data(),member=(await tx.get(db.collection('academyStudentMemberships').doc(key))).data();if(!s||s.issue||s.fields.archived||!member||member.academyId!==actor.academyId)throw Error('FORBIDDEN');const aliases=new Set([id,old?.notionPageId].filter(Boolean)),links=(s.fields.properties['소속반']?.relation||[]).map((v:any)=>uuid(v.id)).filter((key:string)=>!aliases.has(key));if(v.students.includes(key))links.push(id);studentChanges.push({ref:sr,old:s,links});}
  }else{const v:any=value;if(v.classId){const c=(await tx.get(db.collection('teacherClasses').doc(v.classId))).data();if(!c||c.archived||c.subject!==v.subject||!canAccessOwned(actor,c.ownerUid,c.academyId))throw Error('FORBIDDEN');}prepared={...v,isCommon:!v.classId};}
  const at=Date.now(),next={...old,...prepared,ownerUid:old?.ownerUid||actor.uid,academyId:actor.academyId,sourceMode:'firestore',notionSyncStage:'app_saved',notionSyncRequired:false,revision:(old?.revision||0)+1,updatedAt:at};tx.set(ref,next);tx.set(db.collection(MANAGED_HISTORY).doc(`${collection(kind)}:${id}:${next.revision}`),{before:old||null,after:next,by:actor.uid,at,reason:'app-edit'});
  for(const s of studentChanges){const fields={...s.old.fields,properties:{...s.old.fields.properties,'소속반':{relation:s.links.map((id:string)=>({id}))}}},row={...s.old,fields,hash:hash(fields),revision:s.old.revision+1,appEditedAt:new Date(Math.max(at,Date.parse(s.old.appEditedAt||s.old.remoteEditedAt)+1)).toISOString()};tx.set(s.ref,row);tx.set(db.collection(DIRECTORY_HISTORY).doc(`${s.ref.id}:${row.revision}`),{before:s.old.fields,after:fields,sourceKey:s.old.sourceKey,notionPageId:s.old.notionPageId,revision:row.revision,by:actor.uid,at,reason:'class-membership'});}
  return {id,revision:next.revision,record:{id,...next},sourceMode:'firestore'};
 });
}
export async function archiveManaged(db:any,actor:any,kind:Kind,id:string,revision:number){if(!await coreActive(db,actor))throw Error('CORE_NOT_READY');const ref=db.collection(collection(kind)).doc(z.string().uuid().parse(id));return db.runTransaction(async(tx:any)=>{const old=(await tx.get(ref)).data();if(!old||!canAccessOwned(actor,old.ownerUid,old.academyId))throw Error('FORBIDDEN');if(old.archived)return {archived:true};if(old.revision!==revision)throw Error('DRAFT_CONFLICT');const next={...old,archived:true,revision:old.revision+1,updatedAt:Date.now()};tx.set(ref,next);tx.set(db.collection(MANAGED_HISTORY).doc(`${collection(kind)}:${id}:${next.revision}`),{before:old,after:next,by:actor.uid,at:Date.now(),reason:'archive'});return {archived:true};});}

