import { randomUUID } from 'node:crypto';
import { z } from 'zod';
export function workspaceError(error: unknown, failureStage: string) {
 const raw = error instanceof Error ? error.message : '';
 const allowed = ['MESSAGE_VARIABLE_REQUIRED','MESSAGE_CONTACT_REQUIRED','MESSAGE_CONTACT_CHANGED','MESSAGE_CONFIG_REQUIRED','MESSAGE_CONFIRM_REQUIRED','MESSAGE_CONFLICT','MESSAGE_NOT_READY','MESSAGE_DUPLICATE','STUDENT_PROFILE_CONTACT_PENDING','NOTION_SUBJECT_NOT_CONFIGURED','NOTION_WRITE_REQUEST_CONFLICT','NOTION_WRITE_PENDING','NOTION_WRITE_RESULT_UNCERTAIN','SCHEDULE_PROJECTION_LIMIT','DUPLICATE_NOTION_RECORD','STUDENT_ENROLLMENT_REQUEST_CONFLICT','STUDENT_ENROLLMENT_IN_PROGRESS','STUDENT_ENROLLMENT_RESULT_UNCERTAIN','STUDENT_PROFILE_REQUEST_CONFLICT','STUDENT_PROFILE_IN_PROGRESS','STUDENT_PROFILE_RESULT_UNCERTAIN','STUDENT_PROFILE_AUTH_CONFLICT','STUDENT_MAPPING_CONFLICT','NOTION_REGISTRATION_ASSIGNMENT_REQUIRED','NOTION_REGISTRATION_SOURCE_REQUIRED','NOTION_REGISTRATION_SCHEMA_REQUIRED','NOTION_REGISTRATION_ID_MISMATCH','NOTION_REGISTRATION_DUPLICATE','NOTION_REGISTRATION_CREATE_UNCERTAIN','NOTION_REGISTRATION_SYNC_FAILED','REGISTRATION_REQUEST_CONFLICT','REGISTRATION_CONFLICT','REGISTRATION_SYNC_IN_PROGRESS','REGISTRATION_NOT_FOUND','COMMON_PLAN_NOT_SYNCED','INVALID_INPUT','UNAUTHORIZED','SESSION_REVOKED','FORBIDDEN','TEACHER_NOT_CONFIGURED','DRAFT_CONFLICT','SOURCE_IDENTITY_LOCKED','PUBLISH_IN_PROGRESS','NOTION_SCHEMA_SETUP_REQUIRED','MAKE_TRIGGER_NOT_CONFIGURED','MAKE_TRIGGER_FAILED','MAKE_SUBJECT_NOT_CONFIGURED','TEACHER_NOTION_LINK_REQUIRED','LESSON_CONTENT_REQUIRED','LESSON_ROUNDS_REQUIRED','SELF_STUDY_REQUIRED','LESSON_OR_STUDY_REQUIRED','ACADEMY_REQUIRED','INVALID_TEACHER','ACADEMY_MIGRATION_REQUIRED','ACADEMY_MEMBERSHIP_CONFLICT','NOTION_EDIT_CONFLICT','NOTION_SOURCE_NOT_CONFIGURED','NOTION_SOURCE_MISMATCH','NOTION_SHARED_TIMETABLE','NOTION_SOURCE_OWNER_CONFLICT','NOTION_DUPLICATE_ENROLLMENT','NOTION_ENROLLMENT_REQUIRED','NOTION_DUPLICATE_SOURCE'];
 const config = raw.startsWith('CONFIG_ERROR') || raw === 'AUTH_SERVER_CONFIG_ERROR';
 const notion = /^NOTION_/.test(raw);
 const missingIndex = failureStage === 'report-review' && /requires an index|FAILED_PRECONDITION.*index/i.test(raw);
 const code = error instanceof z.ZodError ? 'INVALID_INPUT' : missingIndex ? 'REPORT_INDEX_REQUIRED' : config ? 'SERVER_CONFIG_ERROR' : allowed.includes(raw) ? raw : notion ? 'NOTION_CONNECTION_ERROR' : 'WORKSPACE_ERROR';
 const diagnosticId = randomUUID();
 const messages: Record<string,string> = {SERVER_CONFIG_ERROR:'서버 인증·연결 설정을 확인해야 합니다.',UNAUTHORIZED:'로그인 인증이 만료되었습니다. 다시 로그인해 주세요.',SESSION_REVOKED:'로그인이 해제되었습니다. 다시 로그인해 주세요.',NOTION_CONNECTION_ERROR:'Notion 연결 권한과 데이터베이스 설정을 확인해야 합니다.',LESSON_ROUNDS_REQUIRED:'수업이 있는 날은 출결과 수업 회차를 입력해 주세요.',SELF_STUDY_REQUIRED:'자습 여부를 선택하고, 자습이 있는 날은 시간과 회차를 입력해 주세요.',LESSON_OR_STUDY_REQUIRED:'수업 또는 자습 중 하나 이상을 기록해 주세요.'};
 messages.MESSAGE_VARIABLE_REQUIRED='치환하지 않은 변수를 입력하거나 해당 항목을 삭제해 주세요.';
messages.MESSAGE_CONTACT_REQUIRED='보호자 연락처를 확인해 주세요.';
messages.MESSAGE_CONTACT_CHANGED='보호자 연락처가 변경되었습니다. 새 문자 요청을 준비해 주세요.';
messages.MESSAGE_CONFIG_REQUIRED='서버 Bati 주소와 문자본문 매개변수 설정을 확인해 주세요.';
messages.MESSAGE_CONFIRM_REQUIRED='수신자와 본문을 최종 확인해 주세요.';
messages.MESSAGE_CONFLICT='저장한 문자 요청과 내용이 다릅니다. 새로 열어 주세요.';
messages.MESSAGE_NOT_READY='문자본문을 노션에 저장한 뒤 발송할 수 있습니다.';
messages.MESSAGE_DUPLICATE='동일 수신자와 본문의 발송 요청이 이미 있습니다. 발송 이력을 확인해 주세요.';
messages.STUDENT_PROFILE_CONTACT_PENDING='보호자 연락처 변경을 먼저 완료해 주세요.';
 messages.NOTION_SHARED_DATA_REQUIRED='기존 반·커리큘럼의 담당 선생님·과목·학원 연결을 먼저 확인해 주세요.';
 messages.NOTION_LEGACY_MIGRATION_REQUIRED='기존 선생님별 DB 자료를 공용 DB로 옮긴 뒤 공용 연결을 시작해 주세요.';
 messages.NOTION_TEACHER_ID_CONFLICT='같은 노션 선생님 페이지가 여러 계정에 연결되어 있습니다. 관리자 설정을 확인해 주세요.';
 messages.NOTION_EDIT_CONFLICT='노션에서 이 자료가 변경되었습니다. 새로고침하고 다시 선택한 뒤 수정해 주세요.';
 messages.NOTION_SOURCE_NOT_CONFIGURED='이 선생님의 과목별 노션 DB를 관리자 설정에서 연결해 주세요.';
 messages.NOTION_SOURCE_OWNER_CONFLICT='같은 반 또는 커리큘럼 DB가 여러 선생님에게 연결되어 있습니다. 소속과 담당 DB 연결을 확인해 주세요.';
 messages.NOTION_SOURCE_MISMATCH='연결한 노션 DB와 자료의 원본 DB가 다릅니다. DB 연결을 확인해 주세요.';
 messages.NOTION_ENROLLMENT_REQUIRED='DB_수강에 학생당 하나의 수강 페이지가 필요합니다.';
 messages.NOTION_DUPLICATE_ENROLLMENT='DB_수강에 동일 학생의 페이지가 여러 개 있습니다. 중복을 확인해 주세요.';
 messages.NOTION_DUPLICATE_SOURCE='한 과목에는 DB 연결을 하나만 등록해 주세요.';
 messages.NOTION_SHARED_TIMETABLE='여러 반이 공동 사용 중인 시간표입니다. 해당 반 전용 시간대로 분리한 뒤 수정해 주세요.';
 messages.ACADEMY_MIGRATION_REQUIRED='이미 연결된 선생님의 학원 변경은 기존 기록을 함께 이전해야 합니다.';
 messages.ACADEMY_MEMBERSHIP_CONFLICT='다른 학원에 연결된 학생이 포함되어 있습니다. 소속 학원을 확인해 주세요.';
 messages.COMMON_PLAN_NOT_SYNCED='공통 교재를 먼저 노션에 반영한 뒤 반에서 선택해 주세요.';
 messages.NOTION_REGISTRATION_ASSIGNMENT_REQUIRED='담당 선생님의 소속·재직·과목 또는 반의 담당·상태가 변경되었습니다. 등록 내용을 확인해 주세요.';
 messages.NOTION_REGISTRATION_SOURCE_REQUIRED='이 학원의 학생·수강 노션 연결을 확인해야 합니다.';
 messages.NOTION_REGISTRATION_SCHEMA_REQUIRED='학생·수강 DB의 학교와 앱 등록 ID 등 연결 속성을 확인해 주세요.';
 messages.NOTION_REGISTRATION_ID_MISMATCH='노션 기록의 원본과 학생 연결이 일치하지 않아 반영을 멈췄습니다.';
 messages.NOTION_REGISTRATION_DUPLICATE='같은 앱 등록 ID의 노션 행이 여러 개입니다. 중복을 확인해 주세요.';
 messages.NOTION_REGISTRATION_CREATE_UNCERTAIN='노션 생성 결과를 아직 확인하지 못했습니다. 새로 만들지 않고 기존 행을 다시 확인해 주세요.';
 messages.NOTION_REGISTRATION_SYNC_FAILED='노션 반영 또는 앱 연결에 실패했습니다. 저장한 입력을 유지하며 다시 시도해 주세요.';
 messages.REGISTRATION_REQUEST_CONFLICT='같은 저장 요청의 내용이 달라졌습니다. 저장한 등록 내용을 다시 열어 주세요.';
 messages.REGISTRATION_CONFLICT='다른 화면에서 등록 내용을 수정했습니다. 목록에서 다시 열어 주세요.';
 messages.REGISTRATION_SYNC_IN_PROGRESS='노션 반영 결과를 확인한 뒤 수정할 수 있습니다.';
 messages.REGISTRATION_NOT_FOUND='저장한 등록 내용을 찾을 수 없습니다.';
 messages.STUDENT_PROFILE_REQUEST_CONFLICT='같은 수정 요청의 내용이 달라졌습니다. 학생 정보를 다시 열어 주세요.';
 messages.STUDENT_PROFILE_IN_PROGRESS='학생 정보 수정이 진행 중입니다. 저장 결과를 먼저 확인해 주세요.';
 messages.STUDENT_PROFILE_RESULT_UNCERTAIN='노션 수정 결과를 확인하지 못했습니다. 입력을 유지하고 저장 결과 확인을 다시 눌러 주세요.';
 messages.STUDENT_PROFILE_AUTH_CONFLICT='리포트 인증 정보가 변경되었습니다. 기존 링크 연결을 확인해야 합니다.';
 messages.STUDENT_MAPPING_CONFLICT='학생 식별 연결이 충돌했습니다. 계정 연결을 확인해야 합니다.';
 messages.STUDENT_ENROLLMENT_REQUEST_CONFLICT='저장한 수정 요청의 내용이 달라졌습니다. 수강 관리를 다시 열어 주세요.';
 messages.STUDENT_ENROLLMENT_IN_PROGRESS='수강 변경이 진행 중입니다. 기존 요청의 결과를 먼저 확인해 주세요.';
 messages.STUDENT_ENROLLMENT_RESULT_UNCERTAIN='노션 반영 결과를 아직 확인하지 못했습니다. 저장한 요청으로 결과를 다시 확인해 주세요.';
 messages.NOTION_SUBJECT_NOT_CONFIGURED='이 과목의 노션 수업일지 DB 연결을 확인해 주세요.';
 messages.NOTION_WRITE_REQUEST_CONFLICT='저장한 노션 반영 요청과 내용이 다릅니다. 기존 요청 결과를 먼저 확인해 주세요.';
 messages.NOTION_WRITE_PENDING='노션 반영이 완료되지 않은 요청이 있습니다. 기존 반영 요청을 다시 확인해 주세요.';
 messages.NOTION_WRITE_RESULT_UNCERTAIN='노션 저장 결과를 아직 확인하지 못했습니다. 새 기록을 만들지 않고 기존 요청으로 결과를 다시 확인해 주세요.';
 messages.SCHEDULE_PROJECTION_LIMIT='일정의 누적 대상 수가 동시 반영 한도를 초과했습니다. 일정 연결을 확인해야 합니다.';
 messages.DUPLICATE_NOTION_RECORD='같은 앱 기록 ID의 노션 행이 여러 개입니다. 중복을 확인해 주세요.';
 messages.LESSON_CONTENT_REQUIRED='수업 내용을 입력해 주세요.';
 messages.INVALID_INPUT='입력한 값과 중복된 교재 선택을 확인해 주세요.';
 messages.REPORT_INDEX_REQUIRED = '리포트 조회에 필요한 서버 인덱스 설정을 확인해야 합니다.';
 return {status: ['UNAUTHORIZED','SESSION_REVOKED'].includes(code) ? 401 : code === 'FORBIDDEN' ? 403 : code === 'REGISTRATION_NOT_FOUND' ? 404 : ['SERVER_CONFIG_ERROR','WORKSPACE_ERROR','REPORT_INDEX_REQUIRED'].includes(code) ? 500 : code === 'NOTION_EDIT_CONFLICT' ? 409 : code === 'NOTION_CONNECTION_ERROR' ? 502 : code === 'INVALID_INPUT' || code.includes('REQUIRED') ? 400 : 409, body:{ok:false,error:code,message:messages[code],failureStage,diagnosticId}};
}
