import test from 'node:test';import assert from 'node:assert/strict';import {academicBatchPayload,academicBatchError,saveAcademicBatchRow,applyAcademicBatch,applyAcademicBatchChunks} from '../src/lib/academicBatch';import {readFileSync} from 'node:fs';
const common={subject:'영어',examType:'학교 내신',examDetail:'2학기 중간고사',examYear:2026,title:' 같은 시험 ',examDate:'2026-10-08',deadline:null,maxScore:100};
test('common dates/title are shared while scores/status/grade remain per student and real zero is valid',()=>{const a=academicBatchPayload(common,{studentKey:'a',score:0,grade:'A',submissionStatus:'제출 완료'}),b=academicBatchPayload(common,{studentKey:'b',score:83.5,grade:'B',submissionStatus:'제출 완료'});assert.equal(a.examDate,b.examDate);assert.equal(a.title,'같은 시험');assert.equal(a.score,0);assert.equal(b.score,83.5);assert.equal(academicBatchError(a),'');assert.equal(academicBatchError({...a,score:101}).length>0,true);assert.equal(academicBatchError({...a,score:null}).length>0,true);assert.equal(academicBatchPayload(common,{studentKey:'a',score:25,submissionStatus:'미제출'}).score,null);});
test('lost save acknowledgement reconciles exact saved input using the same ID; different data never counts as success',async()=>{const row={id:'stable',payload:academicBatchPayload(common,{studentKey:'a',score:0,submissionStatus:'제출 완료'})};const calls:string[]=[];const result=await saveAcademicBatchRow(async action=>{calls.push(action);if(action==='save-academic')throw Error('LOST');return {record:{id:'stable',revision:1,data:row.payload}};},row);assert.equal(result.id,'stable');assert.deepEqual(calls,['save-academic','read:managed-record']);await assert.rejects(saveAcademicBatchRow(async action=>{if(action==='save-academic')throw Error('LOST');return {record:{data:{...row.payload,score:99}}};},row),/LOST/);});
test('single and group input share the established initials combobox; reflection saves when required and deletion is enabled',()=>{const single=readFileSync(new URL('../src/components/teacher/TeacherAcademicManager.tsx',import.meta.url),'utf8'),batch=readFileSync(new URL('../src/components/teacher/AcademicBatchEditor.tsx',import.meta.url),'utf8');assert.match(single,/<StudentCombobox students={writableStudents}/);assert.match(batch,/<StudentCombobox disabled={working\s*\|\|\s*frozen}/);assert.match(single,/persist\(true\)/);assert.match(single,/saveAcademicBatchRow/);assert.match(single,/입력 지우기/);assert.match(batch,/저장 포함/);assert.match(batch,/crypto.randomUUID/);});

test('mixed batch keeps success and saved-but-unpublished rows separate and retries only failed reflection',async()=>{const rows=[{id:'a',phase:'new',payload:academicBatchPayload(common,{studentKey:'a',score:0,submissionStatus:'제출 완료'})},{id:'b',phase:'new',payload:academicBatchPayload(common,{studentKey:'b',score:80,submissionStatus:'제출 완료'})}];const calls:any[]=[];const results=await applyAcademicBatch(async(action,body)=>{calls.push({action,body});if(action==='save-academic')return {record:{id:body.id,revision:1,data:body.data}};if(body.id==='b')throw Error('PARTIAL');return {record:{id:body.id,revision:1,stage:'published'}};},rows,true,()=>{});assert.deepEqual(results.map(r=>r.phase),['published','failed-publish']);assert.equal(calls[0].body.data.score,0);assert.equal(calls[2].body.data.score,80);let savedCalls=0;await applyAcademicBatch(async(action,body)=>{if(action==='save-academic')savedCalls++;return {record:{id:body.id,revision:1,stage:'published'}};},[{...rows[1],phase:'failed-publish',revision:1}],true,()=>{});assert.equal(savedCalls,0);});

test('large classes use twenty-row chunks and keep individual outcome/revisions',async()=>{const rows=Array.from({length:43},(_,i)=>({id:String(i),phase:'new',payload:academicBatchPayload(common,{studentKey:String(i),score:i,submissionStatus:'제출 완료'})}));const sizes:number[]=[];const result=await applyAcademicBatchChunks(async(action,body)=>{assert.equal(action,'academic-batch');sizes.push(body.rows.length);return {rows:body.rows.map((row:any)=>({id:row.id,ok:true,phase:'published',record:{revision:1}}))};},rows,true,()=>{});assert.deepEqual(sizes,[20,20,3]);assert.equal(result.length,43);assert.ok(result.every(row=>row.phase==='published'));});
