import {handleWorkspace} from '../api/teacher/workspace.js';
import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {templateFirestore} from './helpers/templateFirestore.js';import {saveAppAcademic,publishAppAcademic,archiveAppAcademic,listAppAcademicSources} from '../api/_lib/appAcademic.js';import {hashStudentKey} from '../api/_lib/security.js';import {syncAcademicPage,GRADE_DATABASE} from '../api/_lib/academic.js';
const student='11111111-1111-4111-8111-111111111111';
function fixture(){const f=templateFirestore(),actor={uid:'t',admin:false,academyId:'main',scopes:[{studentKey:student,subject:'영어'}]};f.rows.set('academyStudentMemberships/'+student,{academyId:'main',internalStudentId:'internal',disabled:false});f.rows.set('notionStudentMappings/'+hashStudentKey(student),{studentKey:student,internalStudentId:'internal',origin:'app',notionStudentPageId:null,studentDisplayName:'모의 학생'});f.rows.set('teacherWorkspaceAccess/t',{academyId:'main',scopes:actor.scopes});f.rows.set('academyCoreAuthority/main',{active:true});const data={studentKey:student,subject:'영어',examType:'학교 내신',examDetail:'2학기 중간고사',examYear:2026,semester:2,examPeriod:'중간고사',title:'모의 시험',examDate:'2026-10-08',deadline:null,score:0,maxScore:100,grade:'A',submissionStatus:'제출 완료',note:'비공개 비고'};return {...f,actor,data};}
test('draft stays private, publication is atomic/idempotent, updates retain public identity and stale requests fail',async()=>{const f=fixture(),saved=await saveAppAcademic(f.db,f.actor,{id:randomUUID(),data:f.data});assert.equal([...f.rows.keys()].filter(k=>k.startsWith('academicRecords/')).length,0);const first=await publishAppAcademic(f.db,f.actor,saved.id,1);const key='academicRecords/'+first.record.appProjectionId;assert.equal(f.rows.get(key).score,0);assert.equal(f.rows.get(key).note,undefined);const writes=f.metrics.writes;await publishAppAcademic(f.db,f.actor,saved.id,1);assert.equal(f.metrics.writes,writes);const updated=await saveAppAcademic(f.db,f.actor,{id:saved.id,revision:1,data:{...f.data,score:89}});assert.equal(f.rows.get(key).score,0);await assert.rejects(publishAppAcademic(f.db,f.actor,saved.id,1),/DRAFT_CONFLICT/);await publishAppAcademic(f.db,f.actor,saved.id,updated.record.revision);assert.equal(f.rows.get(key).score,89);assert.equal([...f.rows.keys()].filter(k=>k.startsWith('academicRecords/')).length,1);});
test('failed publish commit exposes no partial report and later retry succeeds',async()=>{const f=fixture(),r=await saveAppAcademic(f.db,f.actor,{id:randomUUID(),data:f.data});const before=structuredClone([...f.rows]);f.failNextCommit();await assert.rejects(publishAppAcademic(f.db,f.actor,r.id,1),/FIRESTORE_UNAVAILABLE/);assert.deepEqual([...f.rows],before);await publishAppAcademic(f.db,f.actor,r.id,1);});
test('revoked scopes, foreign owners/academies and publication target collisions never modify reports',async()=>{for(const kind of ['scope','owner','academy','target']){const f=fixture(),r=await saveAppAcademic(f.db,f.actor,{id:randomUUID(),data:f.data});if(kind==='scope')f.rows.get('teacherWorkspaceAccess/t').scopes=[];if(kind==='owner')f.rows.get('teacherAcademicDrafts/'+r.id).ownerUid='other';if(kind==='academy')f.rows.get('academyStudentMemberships/'+student).academyId='other';if(kind==='target')f.rows.set('academicRecords/app-'+r.id,{internalStudentId:'other-internal'});const before=structuredClone([...f.rows]);await assert.rejects(publishAppAcademic(f.db,f.actor,r.id,1));assert.deepEqual([...f.rows],before);}});
test('archive retains history and tombstones while late Notion deliveries cannot reopen a native grade',async()=>{const f=fixture(),id=randomUUID(),saved=await saveAppAcademic(f.db,f.actor,{id,data:f.data});await publishAppAcademic(f.db,f.actor,id,1);await archiveAppAcademic(f.db,f.actor,id,1);assert.equal(f.rows.get('academicRecords/app-'+id).removed,true);assert.equal(f.rows.get('teacherAcademicDrafts/'+id).archived,true);const page={id:randomUUID(),parent:{database_id:GRADE_DATABASE},last_edited_time:new Date().toISOString(),properties:{'학생':{relation:[{id:student}]},'과목':{select:{name:'영어'}},'시험 종류':{select:{name:'학교 내신'}},'앱 기록 ID':{rich_text:[{plain_text:id}]}}};const result=await syncAcademicPage(f.db as any,page);assert.equal(result.applied,false);assert.equal(result.reason,'APP_OWNED');});
test('Firestore historical sources remain visible to authorized viewers and can be archived without Notion',async()=>{const f=fixture(),id=randomUUID(),at=new Date().toISOString();f.rows.set('academicRecords/'+id,{internalStudentId:'internal',subject:'영어',examType:'학교 내신',title:'과거 시험',examDate:'2026-10-01',score:77,maxScore:100,submissionStatus:'제출 완료',sourceUpdatedAt:at,ownerUid:'t'});const list=await listAppAcademicSources(f.db,f.actor);assert.equal(list.length,1);assert.equal(list[0].data.score,77);await archiveAppAcademic(f.db,f.actor,id,undefined,{studentKey:student,sourceEditedAt:at});assert.equal(f.rows.get('academicRecords/'+id).archived,true);assert.equal((await listAppAcademicSources(f.db,f.actor)).length,0);});

test('expired uncertain Notion grade can be taken over without Notion and advancing revision blocks late completion',async()=>{const f=fixture(),id=randomUUID();f.rows.set('teacherAcademicDrafts/'+id,{ownerUid:'t',academyId:'main',revision:1,stage:'failed',data:f.data,notionWrite:{attempted:true,done:false,leaseUntil:0}});const result=await publishAppAcademic(f.db,f.actor,id,1);assert.equal(result.record.revision,2);assert.equal(result.record.stage,'published');assert.equal(result.record.notionWrite.attempted,true);assert.equal((await publishAppAcademic(f.db,f.actor,id,1)).alreadyPublished,true);const updated=await saveAppAcademic(f.db,f.actor,{id,revision:2,data:{...f.data,score:22}});assert.equal(updated.record.revision,3);await assert.rejects(publishAppAcademic(f.db,f.actor,id,1),/DRAFT_CONFLICT/);});
test('compact original public grade ID is retained rather than creating a second report',async()=>{const f=fixture(),id=randomUUID(),page=randomUUID(),compact=page.replace(/-/g,'');f.rows.set('teacherAcademicDrafts/'+id,{ownerUid:'t',academyId:'main',revision:1,stage:'published',data:f.data,notionPageId:page});f.rows.set('academicRecords/'+compact,{internalStudentId:'internal',score:10,teacherDraftId:id});const result=await publishAppAcademic(f.db,f.actor,id,1);assert.equal(result.record.appProjectionId,compact);assert.equal(f.rows.has('academicRecords/'+page),false);assert.equal(f.rows.get('academicRecords/'+compact).score,0);});

test('batch endpoint preserves per-student records and same-ID retries without duplicate saves',async()=>{const f=fixture(),id=randomUUID(),call=async()=>{let body:any;const res:any={setHeader:()=>{},end:(value:string)=>body=JSON.parse(value)};await handleWorkspace({method:'POST',body:{action:'academic-batch',reflect:true,rows:[{id,saveFirst:true,data:f.data}]}} as any,res,async()=>({...f.actor,db:f.db}));assert.equal(res.statusCode,200);return body;};const first=await call();assert.equal(first.rows[0].record.stage,'published');const second=await call();assert.equal(second.rows[0].record.revision,1);assert.equal([...f.rows.keys()].filter(key=>key.startsWith('teacherAcademicDrafts/')).length,1);});
