import {workspaceError} from '../api/_lib/teacherWorkspaceError.js';
import {syncStudentRegistration} from '../api/_lib/teacherStudentRegistrationSync.js';
import {REGISTRATION_STUDENT_DATABASE} from '../api/_lib/teacherStudentRegistrationNotion.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {templateFirestore} from './helpers/templateFirestore.js';
import {commitAppStudentRegistration} from '../api/_lib/appStudentRegistration.js';
import {saveStudentRegistration,convertRegistrationToResident} from '../api/_lib/teacherStudentRegistration.js';
import {emptyRegistration} from '../src/lib/studentRegistration.js';
import {directoryRowKey,directorySourceKey,readDirectoryStudents} from '../api/_lib/academyDirectorySource.js';
import {readCoreProfile,readCoreEnrollment,saveCoreProfile,cutoverCore} from '../api/_lib/academyCore.js';
import {profileFromPage,profileProperties,studentProfileSchema} from '../api/_lib/teacherStudentProfile.js';
import {readStudentMapping,lookupStudentIdentity} from '../api/_lib/studentIdentity.js';
import {hashStudentKey} from '../api/_lib/security.js';
process.env.PHONE_PIN_PEPPER='p'.repeat(64);
const teacher='teacher',teacherId='22222222-2222-4222-8222-222222222222',klassId='33333333-3333-4333-8333-333333333333';
async function fixture(){const f=templateFirestore(),actor={uid:'admin',admin:true,academyId:'main',coreMode:true};f.rows.set('academyCoreAuthority/main',{active:true});f.rows.set('academyClassAuthority/main',{active:true});f.rows.set('academyDirectorySync/'+directorySourceKey('students'),{ready:true,approved:true,runVersion:1});f.rows.set('users/'+teacher,{role:'teacher'});f.rows.set('teacherWorkspaceAccess/'+teacher,{academyId:'main',workspaceRole:'teacher',notionTeacherPageId:teacherId,scopes:[{studentKey:'44444444-4444-4444-8444-444444444444',subject:'영어'}]});f.rows.set('academyDirectorySources/'+directoryRowKey('teachers',teacherId),{kind:'teachers',academyId:'main',fields:{archived:false,properties:{'상태':{select:{name:'재직'}},'담당 과목':{multi_select:[{name:'영어'}]}}},pointer:{teacherUid:teacher}});f.rows.set('teacherClasses/'+klassId,{academyId:'main',subject:'영어',ownerUid:teacher,teacherUids:[teacher],students:['44444444-4444-4444-8444-444444444444'],status:'진행 중',sourceMode:'firestore',revision:1});f.rows.set('reportSlugs/existing',{internalStudentId:'stable-existing',parentPhonePinHash:'keep',authVersion:4});const input={...emptyRegistration(),name:'모의 신규 학생',guardianPhone:'01012345678',enrollments:[{subject:'영어',status:'등록',startDate:'2026-10-08',endDate:null,teacherUid:teacher,classIds:[klassId]}]};const saved=await saveStudentRegistration(f.db,actor,input,randomUUID(),undefined,randomUUID());return {...f,actor,input,saved};}
test('app registration atomically creates native identities, directory, enrollment, class and scopes; retries preserve IDs',async()=>{const f=await fixture(),before=structuredClone(f.rows.get('reportSlugs/existing'));const [a,b]=await Promise.all([commitAppStudentRegistration(f.db,f.actor,f.saved.id,1),commitAppStudentRegistration(f.db,f.actor,f.saved.id,1)]);assert.equal(a.studentKey,b.studentKey);assert.equal(b.alreadySynced,true);assert.equal([...f.rows.keys()].filter(k=>k.startsWith('notionStudentMappings/')).length,1);const mapping=await readStudentMapping(f.db as any,a.studentKey);assert.equal(mapping?.notionStudentPageId,null);assert.equal(mapping?.origin,'app');assert.equal(mapping?.firebaseUid,null);assert.equal(f.rows.get('teacherClasses/'+klassId).students.length,2);assert.equal(f.rows.get('teacherWorkspaceAccess/'+teacher).scopes.length,2);assert.deepEqual(f.rows.get('reportSlugs/existing'),before);const students=await readDirectoryStudents(f.db,f.actor);assert.equal(students[0].studentKey,a.studentKey);const p=await readCoreProfile(f.db,f.actor,a.studentKey,profileFromPage);assert.equal(p.data.displayName,'모의 신규 학생');const e=await readCoreEnrollment(f.db,f.actor,a.studentKey);assert.equal(e.subjects[0].status,'등록');const identity=await lookupStudentIdentity(f.db as any,a.studentKey);assert.equal(identity.studentKey,a.studentKey);assert.equal(identity.notionStudentPageId,null);await convertRegistrationToResident(f.db,f.actor,f.saved.id,1);assert.ok(f.rows.get('teacherStudentRegistrations/'+f.saved.id).residentAt);});
test('failed commit writes none of the live connections and retry creates only one student',async()=>{const f=await fixture(),before=structuredClone([...f.rows]);f.failNextCommit();await assert.rejects(commitAppStudentRegistration(f.db,f.actor,f.saved.id,1),/FIRESTORE_UNAVAILABLE/);assert.deepEqual([...f.rows],before);await commitAppStudentRegistration(f.db,f.actor,f.saved.id,1);assert.equal([...f.rows.keys()].filter(k=>k.startsWith('notionStudentMappings/')).length,1);});
test('revoked teacher, foreign class, stale intake, missing cutover, foreign actor and uncertain Notion work fail closed',async()=>{for(const change of ['teacher','class','revision','authority','actor','uncertain']){const f=await fixture();if(change==='teacher')f.rows.get('teacherWorkspaceAccess/'+teacher).disabled=true;if(change==='class')f.rows.get('teacherClasses/'+klassId).academyId='other';if(change==='authority')f.rows.get('academyClassAuthority/main').active=false;if(change==='uncertain')f.rows.get('teacherStudentRegistrations/'+f.saved.id).syncStatus='uncertain';const before=structuredClone([...f.rows]);await assert.rejects(commitAppStudentRegistration(f.db,change==='actor'?{...f.actor,admin:false}:f.actor,f.saved.id,change==='revision'?2:1));assert.deepEqual([...f.rows],before);}});
test('new app profile edits preserve app provenance and existing URLs/PINs, and inactive core never falls back to Notion',async()=>{const f=await fixture(),r=await commitAppStudentRegistration(f.db,f.actor,f.saved.id,1),before=structuredClone(f.rows.get('reportSlugs/existing')),profile=await readCoreProfile(f.db,f.actor,r.studentKey,profileFromPage);await saveCoreProfile(f.db,f.actor,r.studentKey,randomUUID(),profile.editedAt,{...profile.data,school:'모의학교'},v=>studentProfileSchema.parse(v),profileFromPage,profileProperties);const mapping=await readStudentMapping(f.db as any,r.studentKey);assert.equal(mapping?.origin,'app');assert.equal(mapping?.notionStudentPageId,null);assert.deepEqual(f.rows.get('reportSlugs/existing'),before);f.rows.set('academyCoreAuthority/main',{active:false});await assert.rejects(lookupStudentIdentity(f.db as any,r.studentKey),/CORE_NOT_READY/);});

test('cutover blocks uncertain legacy creation and late legacy worker cannot issue Notion requests',async()=>{const f=templateFirestore(),actor={uid:'admin',admin:true,academyId:'main'};f.rows.set('teacherStudentRegistrations/pending',{academyId:'main',syncStatus:'uncertain',studentCreateAttempted:true});await assert.rejects(cutoverCore(f.db,actor),/CORE_REGISTRATION_IN_PROGRESS/);const live=await fixture();process.env.NOTION_STUDENT_DATABASE_ID=REGISTRATION_STUDENT_DATABASE;let remote=0;await assert.rejects(syncStudentRegistration(live.db,live.actor,live.saved.id,1,{notion:async()=>{remote++;throw Error('NOTION_BLOCKED');},mapStudent:async()=>{throw Error('UNEXPECTED');},syncEnrollment:async()=>{throw Error('UNEXPECTED');}} as any),/CORE_NOT_READY/);assert.equal(remote,0);});

test('partial legacy student saved without create-attempt marker still blocks cutover',async()=>{const f=templateFirestore();f.rows.set('teacherStudentRegistrations/partial',{academyId:'main',syncStatus:'failed',studentSaved:true,notionStudentPageId:randomUUID()});await assert.rejects(cutoverCore(f.db,{uid:'admin',admin:true,academyId:'main'}),/CORE_REGISTRATION_IN_PROGRESS/);assert.equal(f.rows.has('academyCoreAuthority/main'),false);});

test('registration transition errors have bounded recovery messages without raw server details',()=>{for(const code of ['CORE_REGISTRATION_IN_PROGRESS','REGISTRATION_SOURCE_CONFLICT','REGISTRATION_ID_CONFLICT']){const result=workspaceError(Error(code),'student-registration-sync');assert.equal(result.body.error,code);assert.equal(result.status,409);assert.ok(result.body.message);assert.ok(!result.body.message.includes('undefined'));}});
