import test from 'node:test';
import assert from 'node:assert/strict';
import { registrationFirestore } from './helpers/registrationFirestore.js';
import { storeWebhookLessonReport } from '../api/_lib/lessonWebhookProjection.js';
const id = '11111111-1111-4111-8111-111111111111', key = '22222222-2222-4222-8222-222222222222';
const data: any = { notionPageId: id, notionStudentPageId: key, lessonDateStart: '2026-10-05', feedback: '첫 수업\n과제: 10쪽', vocabularyScore: 0, schoolExamScore: null, category: '수업', sourceUpdatedAt: '2026-10-05T01:00:00Z' };
const mapping = { studentKey: key, internalStudentId: 'stable' };
test('legacy lesson upsert preserves zero and repeated/stale deliveries never replace newer content', async () => { const f = registrationFirestore(); await storeWebhookLessonReport(f.db, data, mapping); assert.equal(f.rows.get('lessonReports/' + id).vocabularyScore, 0); assert.equal(f.rows.get('lessonReports/' + id).derivedAssignment, '10쪽'); await storeWebhookLessonReport(f.db, { ...data, feedback: '수정 내용', sourceUpdatedAt: '2026-10-05T02:00:00Z' }, mapping); assert.equal((await storeWebhookLessonReport(f.db, data, mapping)).reason, 'OLDER_SOURCE'); assert.equal((await storeWebhookLessonReport(f.db, { ...data, sourceUpdatedAt: undefined }, mapping)).reason, 'OLDER_SOURCE'); assert.equal(f.rows.get('lessonReports/' + id).feedback, '수정 내용'); });
test('direct app lesson blocks Make even with a forged newer date and compact page ID', async () => { const f = registrationFirestore(); f.rows.set('lessonReports/' + id, { teacherDraftId: 'app', teacherAppRevision: 2, feedback: '앱 입력', internalStudentId: 'stable' }); for (const sourceUpdatedAt of [undefined, '2030-01-01T00:00:00Z']) {
    assert.equal((await storeWebhookLessonReport(f.db, { ...data, notionPageId: id.replace(/-/g, ''), sourceUpdatedAt }, mapping)).reason, 'APP_OWNED');
} assert.equal(f.rows.get('lessonReports/' + id).feedback, '앱 입력'); assert.equal(f.rows.has('lessonReports/' + id.replace(/-/g, '')), false); });
test('legacy compact lesson canonicalization keeps original receive date and rejects reassignment', async () => { const f = registrationFirestore(); f.rows.set('lessonReports/' + id.replace(/-/g, ''), { serverReceivedAt: 'original', internalStudentId: 'stable' }); await storeWebhookLessonReport(f.db, data, mapping); assert.equal(f.rows.get('lessonReports/' + id).serverReceivedAt, 'original'); assert.equal(f.rows.has('lessonReports/' + id.replace(/-/g, '')), false); await assert.rejects(storeWebhookLessonReport(f.db, { ...data, sourceUpdatedAt: '2030-01-01T00:00:00Z' }, { ...mapping, internalStudentId: 'other' }), /SOURCE_IDENTITY_LOCKED/); });
