import test from 'node:test';
import assert from 'node:assert/strict';
import { registrationFirestore } from './helpers/registrationFirestore.js';
import { projectSchedule, generateScheduleDocId, scheduleSourceKey, schedulePayloadFromPage } from '../api/_lib/scheduleProjection.js';
import { hashStudentKey } from '../api/_lib/security.js';
import { scheduleArchivePatch } from '../api/_lib/teacherRecordArchive.js';
const pageId = '11111111-1111-4111-8111-111111111111', draftId = '22222222-2222-4222-8222-222222222222', one = '33333333-3333-4333-8333-333333333333', two = '44444444-4444-4444-8444-444444444444';
const stamp = '2026-10-05T01:00:00.000Z', later = '2026-10-05T02:00:00.000Z';
const input: any = { notionScheduleId: pageId, notionStudentPageIds: [one, two], title: '보강', startAt: '2026-10-08T14:50:00+09:00', endAt: '2026-10-08T16:10:00+09:00', subject: '영어', scheduleType: '기타', status: '예정', notice: '준비물', sourceUpdatedAt: stamp };
function fixture() { const f = registrationFirestore(); for (const [key, id] of [[one, 'one'], [two, 'two']]) {
    f.rows.set('notionStudentMappings/' + hashStudentKey(key), { studentKey: key, notionStudentPageId: key, internalStudentId: id });
    f.rows.set('academyStudentMemberships/' + key, { academyId: 'main', disabled: false });
} f.rows.set('teacherSchedules/' + draftId, { revision: 1 }); return { ...f, app: { draftId, revision: 1, academyId: 'main' }, at: (id: string) => f.rows.get('studentSchedules/' + generateScheduleDocId(pageId, id)), next: () => { f.rows.set('teacherSchedules/' + draftId, { revision: 2 }); return { draftId, revision: 2, academyId: 'main' }; } }; }
test('multiple recipients and repeated projection preserve deterministic IDs, kind and completion dates', async () => { const f = fixture(); await projectSchedule(f.db, { ...input, status: '완료' }, f.app); const before = f.at('one').completedAt; await projectSchedule(f.db, { ...input, status: '완료' }, f.app); assert.equal(f.at('one').completedAt, before); assert.equal(f.at('two').scheduleType, '기타'); assert.equal([...f.rows.keys()].filter(k => k.startsWith('studentSchedules/')).length, 2); assert.equal(generateScheduleDocId(pageId, 'one'), generateScheduleDocId(pageId.replace(/-/g, ''), 'one')); });
test('recipient removal cancels only excluded copies and re-inclusion reuses public IDs', async () => { const f = fixture(); await projectSchedule(f.db, input, f.app); const id = f.at('two').scheduleDocId; await projectSchedule(f.db, { ...input, notionStudentPageIds: [one], sourceUpdatedAt: later }, f.next()); assert.equal(f.at('one').status, '예정'); assert.equal(f.at('two').status, '취소'); f.rows.set('teacherSchedules/' + draftId, { revision: 3 }); await projectSchedule(f.db, { ...input, sourceUpdatedAt: '2026-10-05T03:00:00.000Z' }, { ...f.app, revision: 3 }); assert.equal(f.at('two').status, '예정'); assert.equal(f.at('two').scheduleDocId, id); });
test('delete or empty selection atomically cancels every previously reflected student', async () => { const f = fixture(); await projectSchedule(f.db, input, f.app); await projectSchedule(f.db, { ...input, notionStudentPageIds: [], status: '취소', sourceUpdatedAt: later }, f.next()); assert.equal(f.at('one').status, '취소'); assert.equal(f.at('two').status, '취소'); });
test('late or timestamp-less Make deliveries cannot overwrite managed schedules or uncancel excluded recipients', async () => { const f = fixture(); await projectSchedule(f.db, input, f.app); await projectSchedule(f.db, { ...input, notionStudentPageIds: [one], sourceUpdatedAt: later }, f.next()); for (const sourceUpdatedAt of [undefined, stamp, '2030-01-01T00:00:00Z']) {
    const r = await projectSchedule(f.db, { ...input, notionScheduleId: pageId.replace(/-/g, ''), title: '오래된 문자', sourceUpdatedAt });
    assert.equal(r.reason, 'APP_OWNED');
} assert.equal(f.at('two').status, '취소'); assert.equal(f.at('one').title, '보강'); });
test('unmanaged legacy deliveries enforce source ordering and protect empty-recipient cancellation', async () => { const f = fixture(); await projectSchedule(f.db, input); await projectSchedule(f.db, { ...input, notionStudentPageIds: [], sourceUpdatedAt: later }); assert.equal((await projectSchedule(f.db, input)).reason, 'OLDER_SOURCE'); assert.equal((await projectSchedule(f.db, { ...input, sourceUpdatedAt: undefined })).reason, 'OLDER_SOURCE'); assert.equal(f.at('one').status, '취소'); });
test('failed transaction and invalid membership change no recipient documents', async () => { const f = fixture(); f.failNextCommit(); await assert.rejects(projectSchedule(f.db, input, f.app), /FIRESTORE_UNAVAILABLE/); assert.equal(f.at('one'), undefined); assert.equal(f.at('two'), undefined); await projectSchedule(f.db, input, f.app); const g = fixture(); g.rows.set('academyStudentMemberships/' + two, { academyId: 'other' }); await assert.rejects(projectSchedule(g.db, input, g.app), /ACADEMY_MEMBERSHIP_CONFLICT/); assert.equal(g.at('one'), undefined); });
test('canonical ownership blocks mismatched draft IDs and stale app revisions', async () => { const f = fixture(); await projectSchedule(f.db, input, f.app); await projectSchedule(f.db, { ...input, sourceUpdatedAt: later }, f.next()); assert.equal((await projectSchedule(f.db, input, f.app)).reason, 'OLDER_REVISION'); await assert.rejects(projectSchedule(f.db, input, { ...f.app, draftId: one }), /SOURCE_IDENTITY_LOCKED/); assert.equal(f.rows.get('scheduleSyncStates/' + scheduleSourceKey(pageId)).teacherAppRevision, 2); });
test('Notion schedule parsing preserves all recipients, normalizes changed to upcoming, and archives cancel', () => { const page: any = { id: pageId, last_edited_time: stamp, properties: { '대상 학생': { relation: [{ id: one }, { id: two }] }, '일정명': { title: [{ text: { content: '보강' } }] }, '날짜 및 시간': { date: { start: input.startAt, end: input.endAt } }, '일정 상태': { select: { name: '변경' } } } }; assert.deepEqual(schedulePayloadFromPage(page).notionStudentPageIds, [one, two]); assert.equal(schedulePayloadFromPage(page).status, '예정'); page.archived = true; assert.equal(schedulePayloadFromPage(page).status, '취소'); assert.deepEqual(schedulePayloadFromPage(page).notionStudentPageIds, []); page.properties['대상 학생'].has_more = true; assert.throws(() => schedulePayloadFromPage(page), /NOTION_SCHEMA_SETUP_REQUIRED/); });
test('failed cancellation retries the same revision instead of creating a new intent', () => { const r = { notionPageId: pageId, deleteRequested: true, revision: 2, stage: 'failed', notionWrite: { done: false }, data: { status: '취소' } }; assert.deepEqual(scheduleArchivePatch(r, 2, 123), { stage: 'publishing', publishStartedAt: 123 }); assert.throws(() => scheduleArchivePatch(r, 1, 123), /DRAFT_CONFLICT/); });
