import test from 'node:test';
import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {admissionSchema,admissionBlocks} from '../api/_lib/studentAdmission.js';
import {emptyAdmission} from '../src/lib/studentAdmission.js';
import StudentAdmissionFields from '../src/components/teacher/StudentAdmissionFields';
import {parentLessonDTO,studentLessonDTO} from '../api/_lib/reportAudienceDTO.js';
test('admission preserves zero score, unknown scores, optional fields and invalid dates',()=>{const v=emptyAdmission();v.levels[1].schoolScore=0;v.goal='목표';const parsed=admissionSchema.parse(v);assert.equal(parsed.levels[1].schoolScore,0);assert.equal(parsed.levels[0].schoolScore,null);assert.equal(admissionSchema.safeParse({...v,birthDate:'2026-02-30'}).success,false);assert.equal(admissionSchema.safeParse({...v,levels:[v.levels[0],v.levels[0]]}).success,false);assert.equal(admissionSchema.safeParse({...v,availableDays:['월','월']}).success,false);assert.equal(admissionSchema.safeParse({...v,levels:[{...v.levels[0],schoolScore:101}]}).success,false);assert.deepEqual(admissionSchema.parse(undefined),emptyAdmission());});
test('readable Notion backup keeps zero and chunks long text within limits',()=>{const v=emptyAdmission();v.notes='참고'.repeat(2400);v.address='주소';v.levels[1].schoolScore=0;const blocks=admissionBlocks(admissionSchema.parse(v));const texts=blocks.map((b:any)=>b[b.type].rich_text[0].text.content);assert.ok(texts.every(t=>t.length<=1800));assert.ok(texts.join('\n').includes('내신 점수: 0'));assert.ok(texts.join('\n').includes('주소: 주소'));assert.ok(blocks.length<100);});
test('admission UI has original form sections and explicitly separate consent record',()=>{const html=renderToStaticMarkup(<StudentAdmissionFields value={emptyAdmission()} onChange={()=>{}}/>);for(const label of ['생년월일','알게 된 경로','주소','이전 학습 기간','이전 학원명','사용 교재','현재 수준','국어','영어','수학','과학','학습 목표','수업 가능 요일','가능 시간','참고 사항','개인정보 동의','서명자 이름'])assert.ok(html.includes(label),label);assert.ok(html.includes('원본 서명을 대신하지 않습니다'));assert.ok(html.includes('type="date"'));assert.ok(!html.includes('<details'));assert.ok(html.includes('<table'));});
test('admission details never escape through parent or student lesson DTO',()=>{const r:any={notionPageId:'lesson',lessonDateStart:'2026-10-05',admission:{address:'private address',notes:'private notes'},vocabularyScore:null,schoolExamScore:null};for(const dto of [parentLessonDTO(r),studentLessonDTO(r)])assert.ok(!JSON.stringify(dto).includes('private'));});

test('structured admission properties preserve every field, zero, blank dates and long Unicode without leaking into reports',async()=>{
 const {admissionNotionProperties,admissionNotionSchema,assertAdmissionNotionSchema}=await import('../api/_lib/studentAdmission.js');
 const v=emptyAdmission();v.birthDate='2010-01-02';v.address='주소';v.referral='소개';v.previousPeriod='2년';v.previousAcademy='이전 학원';v.previousBooks='사용 교재';v.previousContent='이전 내용';v.goal='목표';v.availableDays=['월','목'];v.availableTimes='18시';v.notes='😀'.repeat(2400);v.consent='동의';v.consentDate='2026-10-06';v.signerName='서명자';v.signedPaper=true;v.levels[0]={subject:'국어',schoolScore:0,schoolGrade:'A',mockScore:92,mockGrade:'1',diagnostic:'진단'};
 const p=admissionNotionProperties(v,'어머니');assert.deepEqual(Object.keys(p).sort(),Object.keys(admissionNotionSchema).sort());assert.equal(p['생년월일'].date.start,v.birthDate);assert.equal(p['국어 입학 내신 점수'].number,0);assert.equal(p['영어 입학 내신 점수'].number,null);assert.deepEqual(p['수업 가능 요일'].multi_select,[{name:'월'},{name:'목'}]);assert.equal(p['개인정보 동의'].select.name,'동의');assert.equal(p['서명 원서 보관'].checkbox,true);assert.equal(p['보호자 호칭'].rich_text[0].text.content,'어머니');assert.equal(p['상담 참고 사항'].rich_text.map((t:any)=>t.text.content).join(''),v.notes);assert.ok(p['상담 참고 사항'].rich_text.every((t:any)=>t.text.content.length<=1800));assert.equal(admissionNotionProperties(emptyAdmission())['생년월일'].date,null);
 const schema={properties:Object.fromEntries(Object.entries(admissionNotionSchema).map(([key,value])=>[key,{type:Object.keys(value)[0],...value}]))};assert.doesNotThrow(()=>assertAdmissionNotionSchema(schema));schema.properties['생년월일'].type='rich_text';assert.throws(()=>assertAdmissionNotionSchema(schema),/NOTION_ADMISSION_SCHEMA_REQUIRED/);
});
