import test from 'node:test';import assert from 'node:assert/strict';
import {readLessonConflict,resolveLessonConflict} from '../api/_lib/teacherLessonConflict.js';
import {registrationFirestore} from './helpers/registrationFirestore.js';
const id='11111111-1111-4111-8111-111111111111',key='22222222-2222-4222-8222-222222222222',pageId='33333333-3333-4333-8333-333333333333',database='44444444-4444-4444-8444-444444444444';
function fixture(){const f=registrationFirestore();const data:any={studentKey:key,subject:'영어',date:'2026-10-05',classSession:'있음',start:'14:00',end:'15:00',round:1,selfStudy:'없음',attendance:'출석',attitude:'상',homework:'상',test:'없는 날',content:'앱 내용',assignment:'',note:'',nextPlan:'',correct:null,total:null,examCorrect:null,examTotal:null};const properties:any={'학생':{relation:[{id:key}]},'과목':{select:{name:'영어'}},'앱 기록 ID':{rich_text:[{plain_text:id}]},'수업':{title:[{plain_text:'14:00 ~ 15:00'}]},'수업 날짜':{date:{start:'2026-10-05T14:00:00+09:00'}},'수업 내용':{rich_text:[{plain_text:'노션 내용'}]},'회차':{number:1},'출석':{select:{name:'출석'}},'태도':{status:{name:'상'}},'숙제':{status:{name:'상'}},'테스트':{status:{name:'없는 날'}}};const page:any={id:pageId,parent:{database_id:database},last_edited_time:'new',properties};f.rows.set('teacherLessonDrafts/'+id,{ownerUid:'t',revision:1,stage:'report_published_notion_pending',failureCode:'NOTION_EDIT_CONFLICT',notionPageId:pageId,data,notionWrite:{database,pageId,done:true,properties:{'수업 내용':{rich_text:[{text:{content:'앱 내용'}}]}}}});const actor:any={uid:'t',admin:false,scopes:[{studentKey:key,subject:'영어'}],teachingScopes:[{studentKey:key,subject:'영어'}]};let writes=0;const notion:any=async(_p:string,method='GET')=>{if(method!=='GET')writes++;return structuredClone(page);};return {...f,page,actor,notion,writes:()=>writes};}
test('compare and app choice retain page identity and report without external writes',async()=>{const f=fixture();f.rows.set('lessonReports/'+pageId,{reportIdentity:'stable'});const r=await readLessonConflict(f.db,f.actor,id,f.notion);assert.equal(r.fields[0].notion,'노션 내용');await resolveLessonConflict(f.db,f.actor,{id,revision:1,token:r.token,choice:'app'},f.notion);const saved=f.rows.get('teacherLessonDrafts/'+id);assert.equal(saved.notionPageId,pageId);assert.equal(saved.notionEditedAt,'new');assert.equal(saved.data.content,'앱 내용');assert.equal(saved.revision,2);assert.equal(saved.notionWrite,null);assert.equal(f.rows.get('lessonReports/'+pageId).reportIdentity,'stable');assert.equal(f.writes(),0);});
test('Notion choice imports validated managed data',async()=>{const f=fixture();const r=await readLessonConflict(f.db,f.actor,id,f.notion);assert.equal(r.canUseNotion,true);await resolveLessonConflict(f.db,f.actor,{id,revision:1,token:r.token,choice:'notion'},f.notion);assert.equal(f.rows.get('teacherLessonDrafts/'+id).data.content,'노션 내용');});
test('changed Notion snapshot and changed app revision reject stale choices',async()=>{const f=fixture();const r=await readLessonConflict(f.db,f.actor,id,f.notion);f.page.last_edited_time='newer';await assert.rejects(resolveLessonConflict(f.db,f.actor,{id,revision:1,token:r.token,choice:'app'},f.notion),/NOTION_EDIT_CONFLICT/);assert.equal(f.rows.get('teacherLessonDrafts/'+id).revision,1);});
test('wrong owner, live lease and changed student cannot reset frozen intent',async()=>{const f=fixture();await assert.rejects(readLessonConflict(f.db,{...f.actor,uid:'other'},id,f.notion),/FORBIDDEN/);f.rows.get('teacherLessonDrafts/'+id).notionWrite.leaseUntil=Date.now()+10000;await assert.rejects(readLessonConflict(f.db,f.actor,id,f.notion),/PUBLISH_IN_PROGRESS/);f.rows.get('teacherLessonDrafts/'+id).notionWrite.leaseUntil=0;f.page.properties.학생.relation=[{id:pageId}];await assert.rejects(readLessonConflict(f.db,f.actor,id,f.notion),/NOTION_SOURCE_MISMATCH/);});
