import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {registrationFirestore} from './helpers/registrationFirestore.js';
import {prepareTeacherMessage,sendTeacherMessage,batiConfig,readTeacherMessages} from '../api/_lib/teacherMessages.js';
import {renderTeacherMessage,messageVariables} from '../src/lib/teacherMessage.js';
import {hashStudentKey} from '../api/_lib/security.js';
import {templateFirestore} from './helpers/templateFirestore.js';
import {TEMPLATE_COLLECTION,TEMPLATE_STATE,TEMPLATE_SOURCE,TEMPLATE_DATABASE,templateKey,templatePage} from '../api/_lib/messageTemplateStore.js';
const key='11111111-1111-4111-8111-111111111111',templateId='22222222-2222-4222-8222-222222222222',studentDB='e2b0d0f1-c79a-8262-a208-8116c9201cfc';
process.env.NOTION_STUDENT_DATABASE_ID=studentDB;process.env.BATI_WEBHOOK_URL='https://app.bati.ai/webhook/test_only';process.env.BATI_MESSAGE_PARAM='본문';process.env.BATI_RECIPIENT_PARAM='보호자연락처';process.env.BATI_WEBHOOK_METHOD='GET';process.env.BATI_PAYLOAD_MODE='body-only';process.env.BATI_RESPONSE_RULE=JSON.stringify({kind:'status',status:200});
function fixture(){const f=registrationFirestore(),actor={uid:'teacher',admin:false,principal:false,academyId:'main',scopes:[{studentKey:key,subject:'영어'}]};f.rows.set('academyStudentMemberships/'+key,{academyId:'main'});let patches=0,fail=false;
 const page:any={id:key,parent:{database_id:studentDB},last_edited_time:'2026-10-05T00:00:00.000Z',properties:{학생:{title:[{plain_text:'학생'}]},보호자연락처:{phone_number:'01012345678'}}};
 const template:any={id:templateId,parent:{database_id:'ec10d0f1-c79a-8312-946b-811e86041ee2'},properties:{유형:{title:[{plain_text:'인사'}]},'내용(문자본문)':{rich_text:[{plain_text:'{{학생 호칭}} 안녕하세요'}]}}};
 const notion=async(path:string,method='GET',body?:any)=>{if(path.endsWith('/query'))return {results:[template],has_more:false};if(path===`pages/${templateId}`)return template;if(path===`pages/${key}`){if(method==='PATCH'){patches++;if(fail){fail=false;throw Error('NOTION_502');}Object.assign(page.properties,body.properties);}return structuredClone(page);}throw Error(path);};
 const input={action:'prepare-message',id:randomUUID(),studentKey:key,subject:'영어',templateId,lessonId:null,body:'안녕하세요\n수업 안내입니다.'};return {...f,actor,page,notion,input,get patches(){return patches;},failBackup:()=>{fail=true;}};}
test('template escaping and line breaks, zero scores, missing variables',()=>{const vars=messageVariables({displayName:'학생',tuition:0},{correct:0,total:10});assert.equal(vars['단어'],0);assert.equal(vars['수강료'],'0');assert.deepEqual(renderTeacherMessage('\\{\\{학생 호칭\\}\\}<br>{{단어}}점\n{{미상}}',vars),{body:'학생\n0점\n{{미상}}',missing:['미상'],dropped:[]});assert.equal(vars['내신 대비 점수'],undefined);});
test('prepare only writes selected template and body, no sends',async()=>{const f=fixture();const r=await prepareTeacherMessage(f.db,f.actor,f.input,f.notion);assert.equal(r?.status,'ready');assert.deepEqual(Object.keys(f.page.properties).sort(),['학생','보호자연락처','메시지템플릿선택','완성된 문자본문'].sort());assert.equal(f.patches,1);await prepareTeacherMessage(f.db,f.actor,f.input,f.notion);assert.equal(f.patches,1);});
test('backup failure resumes immutable request and rejects changed input',async()=>{const f=fixture();f.failBackup();await assert.rejects(prepareTeacherMessage(f.db,f.actor,f.input,f.notion),/NOTION_502/);assert.equal(f.rows.get('teacherMessages/'+f.input.id).status,'prepared');await assert.rejects(prepareTeacherMessage(f.db,f.actor,{...f.input,body:'다른 내용'},f.notion),/MESSAGE_CONFLICT/);assert.equal((await prepareTeacherMessage(f.db,f.actor,f.input,f.notion))?.status,'ready');});
test('permission, wrong source, unresolved placeholders and missing contact reject',async()=>{const f=fixture();await assert.rejects(prepareTeacherMessage(f.db,{...f.actor,scopes:[]},f.input,f.notion),/FORBIDDEN/);await assert.rejects(prepareTeacherMessage(f.db,f.actor,{...f.input,body:'{{학생}}'},f.notion),/MESSAGE_VARIABLE_REQUIRED/);f.page.parent.database_id=templateId;await assert.rejects(prepareTeacherMessage(f.db,f.actor,f.input,f.notion),/NOTION_SOURCE_MISMATCH/);f.page.parent.database_id=studentDB;f.page.properties.보호자연락처.phone_number='';await assert.rejects(prepareTeacherMessage(f.db,f.actor,f.input,f.notion),/MESSAGE_CONTACT_REQUIRED/);});
test('double click and replay issue one request; accepted means request accepted',async()=>{const f=fixture();await prepareTeacherMessage(f.db,f.actor,f.input,f.notion);let calls=0;const transport:any=async(url:URL,options:any)=>{calls++;assert.equal(url.searchParams.get('보호자연락처'),'01012345678');assert.equal(url.searchParams.get('본문'),f.input.body);assert.equal(options.redirect,'manual');return {ok:true,status:200};};await Promise.all([sendTeacherMessage(f.db,f.actor,f.input.id,true,f.notion,transport),sendTeacherMessage(f.db,f.actor,f.input.id,true,f.notion,transport)]);await sendTeacherMessage(f.db,f.actor,f.input.id,true,f.notion,transport);assert.equal(calls,1);assert.equal(f.rows.get('teacherMessages/'+f.input.id).status,'accepted');const another={...f.input,id:randomUUID()};await prepareTeacherMessage(f.db,f.actor,another,f.notion);await assert.rejects(sendTeacherMessage(f.db,f.actor,another.id,true,f.notion,transport),/MESSAGE_DUPLICATE/);assert.equal(calls,1);});
for(const mode of ['timeout','redirect','http500'])test(`${mode} blocks every resend`,async()=>{const f=fixture();await prepareTeacherMessage(f.db,f.actor,f.input,f.notion);let calls=0;const transport:any=async()=>{calls++;if(mode==='timeout')throw Error('timeout');return {ok:false};};assert.equal((await sendTeacherMessage(f.db,f.actor,f.input.id,true,f.notion,transport))?.status,'uncertain');await sendTeacherMessage(f.db,f.actor,f.input.id,true,f.notion,transport);assert.equal(calls,1);});
test('final confirmation, changed phone, pending contact and revoked membership block sending',async()=>{const f=fixture();await prepareTeacherMessage(f.db,f.actor,f.input,f.notion);const transport:any=async()=>{throw Error('should not send');};await assert.rejects(sendTeacherMessage(f.db,f.actor,f.input.id,false,f.notion,transport),/MESSAGE_CONFIRM_REQUIRED/);f.page.properties.보호자연락처.phone_number='01099999999';await assert.rejects(sendTeacherMessage(f.db,f.actor,f.input.id,true,f.notion,transport),/MESSAGE_CONTACT_CHANGED/);f.page.properties.보호자연락처.phone_number='01012345678';f.rows.set('teacherStudentEdits/'+hashStudentKey(key),{contactChanged:true,status:'uncertain'});await assert.rejects(sendTeacherMessage(f.db,f.actor,f.input.id,true,f.notion,transport),/STUDENT_PROFILE_CONTACT_PENDING/);f.rows.delete('teacherStudentEdits/'+hashStudentKey(key));f.rows.set('academyStudentMemberships/'+key,{academyId:'main',disabled:true});await assert.rejects(sendTeacherMessage(f.db,f.actor,f.input.id,true,f.notion,transport),/FORBIDDEN/);});
test('transaction failure before sending produces no network side effect',async()=>{const f=fixture();await prepareTeacherMessage(f.db,f.actor,f.input,f.notion);let calls=0;f.failNextCommit();await assert.rejects(sendTeacherMessage(f.db,f.actor,f.input.id,true,f.notion,(async()=>{calls++;return {ok:true,status:200};}) as any),/FIRESTORE_UNAVAILABLE/);assert.equal(calls,0);assert.equal(f.rows.get('teacherMessages/'+f.input.id).status,'ready');});
test('lost result persistence remains sending and cannot resend',async()=>{const f=fixture();await prepareTeacherMessage(f.db,f.actor,f.input,f.notion);let calls=0;const transport:any=async()=>{calls++;f.failNextCommit();return {ok:true,status:200};};await assert.rejects(sendTeacherMessage(f.db,f.actor,f.input.id,true,f.notion,transport),/FIRESTORE_UNAVAILABLE/);assert.equal((await sendTeacherMessage(f.db,f.actor,f.input.id,true,f.notion,transport))?.status,'sending');assert.equal(calls,1);});
test('listing templates and lessons respects subject and academy',async()=>{const f=fixture();f.rows.set('teacherLessonDrafts/'+randomUUID(),{academyId:'main',stage:'published',data:{studentKey:key,subject:'영어',date:'2026-10-05'}});f.rows.set('teacherLessonDrafts/'+randomUUID(),{academyId:'main',stage:'published',data:{studentKey:key,subject:'수학',date:'2026-10-05'}});const r=await readTeacherMessages(f.db,f.actor,key,'영어',f.notion);assert.equal(r.templates.length,1);assert.equal(r.lessons.length,1);await assert.rejects(readTeacherMessages(f.db,f.actor,key,'수학',f.notion),/FORBIDDEN/);});
test('webhook configuration refuses external host, credentials and query',()=>{const original=process.env.BATI_WEBHOOK_URL;for(const value of ['http://app.bati.ai/webhook/key','https://evil.test/webhook/key','https://x:password@app.bati.ai/webhook/key','https://app.bati.ai/webhook/key?x=1']){process.env.BATI_WEBHOOK_URL=value;assert.throws(batiConfig,/MESSAGE_CONFIG_REQUIRED/);}process.env.BATI_WEBHOOK_URL=original;});
test('message parameter cannot overwrite recipient or contain control characters',()=>{const original=process.env.BATI_MESSAGE_PARAM;try{for(const name of ['보호자연락처',' body','body\n']){process.env.BATI_MESSAGE_PARAM=name;assert.throws(batiConfig,/MESSAGE_CONFIG_REQUIRED/);}}finally{process.env.BATI_MESSAGE_PARAM=original;}});
test('membership removed during source lookup blocks prepare before backup',async()=>{const f=fixture();const n:any=async(path:string,method?:string,body?:any)=>{const value=await f.notion(path,method,body);if(path===`pages/${templateId}`)f.rows.delete('academyStudentMemberships/'+key);return value;};await assert.rejects(prepareTeacherMessage(f.db,f.actor,f.input,n),/FORBIDDEN/);assert.equal(f.patches,0);assert.equal(f.rows.has('teacherMessages/'+f.input.id),false);});
test('unknown acceptance contract blocks before lock or network and leaves prepared body reusable',async()=>{
 const f=fixture();await prepareTeacherMessage(f.db,f.actor,f.input,f.notion);const prior=process.env.BATI_RESPONSE_RULE;delete process.env.BATI_RESPONSE_RULE;let calls=0;
 try{await assert.rejects(sendTeacherMessage(f.db,f.actor,f.input.id,true,f.notion,(async()=>{calls++;return new Response();}) as any),/MESSAGE_CONFIG_REQUIRED/);assert.equal(calls,0);assert.equal(f.rows.get('teacherMessages/'+f.input.id).status,'ready');assert.equal([...f.rows.keys()].filter(k=>k.startsWith('teacherMessageSendLocks/')).length,0);}finally{process.env.BATI_RESPONSE_RULE=prior;}
});
test('HTML 200 does not count as confirmed JSON acceptance or permit resend',async()=>{
 const f=fixture();await prepareTeacherMessage(f.db,f.actor,f.input,f.notion);const prior=process.env.BATI_RESPONSE_RULE;process.env.BATI_RESPONSE_RULE=JSON.stringify({kind:'json',status:200,path:['success'],equals:true});let calls=0;
 try{const transport:any=async()=>{calls++;return new Response('<html>완료 페이지</html>',{status:200});};const result=await sendTeacherMessage(f.db,f.actor,f.input.id,true,f.notion,transport);assert.equal(result?.status,'uncertain');assert.equal(result?.httpStatus,200);assert.equal(result?.outcomeCode,'response-unconfirmed');await sendTeacherMessage(f.db,f.actor,f.input.id,true,f.notion,transport);assert.equal(calls,1);}finally{process.env.BATI_RESPONSE_RULE=prior;}
});
test('contact edit begins during source lookup blocks preparation transaction',async()=>{const f=fixture();const n:any=async(path:string,method?:string,body?:any)=>{const value=await f.notion(path,method,body);if(path===`pages/${templateId}`)f.rows.set('teacherStudentEdits/'+hashStudentKey(key),{contactChanged:true,status:'uncertain'});return value;};await assert.rejects(prepareTeacherMessage(f.db,f.actor,f.input,n),/STUDENT_PROFILE_CONTACT_PENDING/);assert.equal(f.patches,0);});
test('Firestore template cutover removes only template Notion reads; existing preparation/recipient checks stay intact',async()=>{
 const previous=process.env.MESSAGE_TEMPLATE_READ_MODE,f=fixture(),t=templateFirestore();
 const page={id:templateId,parent:{database_id:TEMPLATE_DATABASE},last_edited_time:'2026-10-07T00:00:00Z',properties:{'유형':{title:[{plain_text:'앱 템플릿'}]},'내용(문자본문)':{rich_text:[{plain_text:'{{학생 호칭}} 앱 본문'}]},'대상':{select:{name:'보호자'}}}};
 const p=templatePage(page);t.rows.set(TEMPLATE_STATE+'/'+TEMPLATE_SOURCE,{ready:true});t.rows.set(TEMPLATE_COLLECTION+'/'+templateKey(templateId),{sourceKey:TEMPLATE_SOURCE,academyId:'main',databaseId:TEMPLATE_DATABASE,notionPageId:templateId,data:p.data,dataHash:p.hash,revision:1,status:'synced'});
 const db={...f.db,collection:(name:string)=>name.startsWith('messageTemplate')?t.db.collection(name):f.db.collection(name)};
 const paths:string[]=[];const notion:any=async(path:string,method?:string,body?:any)=>{paths.push(path);return f.notion(path,method,body);};
 try{
  process.env.MESSAGE_TEMPLATE_READ_MODE='notion';await readTeacherMessages(db,f.actor,key,'영어',notion);assert.equal(paths.filter(p=>p.endsWith('/query')).length,1);
  const legacy=fixture();await prepareTeacherMessage(legacy.db,legacy.actor,legacy.input,legacy.notion);const before=legacy.rows.get('teacherMessages/'+legacy.input.id);
  paths.length=0;process.env.MESSAGE_TEMPLATE_READ_MODE='firestore';const r=await readTeacherMessages(db,f.actor,key,'영어',notion);assert.equal(r.templates[0].title,'앱 템플릿');assert.equal(paths.filter(p=>p.endsWith('/query')).length,0);assert.ok(paths.includes('pages/'+key));
  paths.length=0;await prepareTeacherMessage(db,f.actor,f.input,notion);assert.equal(paths.filter(p=>p==='pages/'+templateId).length,0);assert.equal(f.rows.get('teacherMessages/'+f.input.id).context['메시지템플릿선택'],'');assert.equal(f.patches,1); // Preserve the existing title-property context contract.
  const after=f.rows.get('teacherMessages/'+f.input.id);assert.deepEqual({body:after.body,recipient:after.recipient,context:after.context},{body:before.body,recipient:before.recipient,context:before.context});
  await assert.rejects(readTeacherMessages(db,{...f.actor,scopes:[]},key,'영어',notion),/FORBIDDEN/);
 }finally{previous===undefined?delete process.env.MESSAGE_TEMPLATE_READ_MODE:process.env.MESSAGE_TEMPLATE_READ_MODE=previous;}
});

import {directoryRowKey} from '../api/_lib/academyDirectorySource.js';
test('after the core cutover an app-registered student can be messaged with no Notion page and no Notion backup write',async()=>{
 const f=fixture();let notionCalls=0;const notion=async(path:string,method='GET',body?:any)=>{notionCalls++;return f.notion(path,method,body);};
 f.rows.set('academyCoreAuthority/main',{active:true});
 f.rows.set('academyDirectorySources/'+directoryRowKey('students',key),{kind:'students',academyId:'main',origin:'app',databaseId:null,appEditedAt:'2026-10-05T00:00:00.000Z',fields:{properties:{학생:{title:[{plain_text:'앱 학생'}]},보호자연락처:{phone_number:'01012345678'}}}});
 const old=process.env.MESSAGE_TEMPLATE_READ_MODE;process.env.MESSAGE_TEMPLATE_READ_MODE='notion';
 try{
  const prepared=await prepareTeacherMessage(f.db,f.actor,f.input,notion);
  assert.equal(prepared.status,'ready');assert.equal(f.patches,0,'no Notion backup write after cutover');
  assert.equal(prepared.recipient,'01012345678');
  // Only the template read (template mode notion in this test) touched Notion; the student page did not.
  assert.equal(notionCalls,1);
 }finally{if(old===undefined)delete process.env.MESSAGE_TEMPLATE_READ_MODE;else process.env.MESSAGE_TEMPLATE_READ_MODE=old;}
});

test('optional score lines drop out when the lesson has no value',()=>{
 const t='{{학생 호칭}} 수업 결과\n단어 {{단어}}점\n테스트 {{테스트}}\n내신 대비 {{내신 대비 점수}}점\n감사합니다';
 const both=renderTeacherMessage(t,messageVariables({displayName:'민수'},{correct:9,total:10,test:'상',examCorrect:18,examTotal:20}));
 assert.equal(both.body,'민수 수업 결과\n단어 90점\n테스트 상\n내신 대비 90점\n감사합니다');
 const examOnly=renderTeacherMessage(t,messageVariables({displayName:'민수'},{test:'미확인',examCorrect:18,examTotal:20}));
 assert.equal(examOnly.body,'민수 수업 결과\n내신 대비 90점\n감사합니다');assert.deepEqual(examOnly.dropped,['단어','테스트']);assert.deepEqual(examOnly.missing,[]);
 assert.equal(renderTeacherMessage(t,messageVariables({displayName:'민수'},{})).body,'민수 수업 결과\n감사합니다');
 assert.deepEqual(renderTeacherMessage('{{보호자이름}}님',messageVariables({displayName:'민수'},{})).missing,['보호자이름']);
});
