import test from 'node:test';
import assert from 'node:assert/strict';
import {readIntegrityAudit} from '../api/_lib/teacherIntegrityAudit.js';
import {registrationFirestore} from './helpers/registrationFirestore.js';
import {hashStudentKey} from '../api/_lib/security.js';
const k='3e20d0f1-c79a-80a5-bed9-faef008b94c5',other='0fe0d0f1-c79a-838f-8e61-01cd86255ab7',studentDB='e2b0d0f1-c79a-8262-a208-8116c9201cfc',enrollmentDB='3ec0d0f1-c79a-80b2-bb52-ea162888fe9a';
function fixture(){process.env.NOTION_STUDENT_DATABASE_ID=studentDB;const f=registrationFirestore();f.rows.set('academyStudentMemberships/'+k,{academyId:'main'});f.rows.set('notionStudentMappings/'+hashStudentKey(k),{notionStudentPageId:k,internalStudentId:'internal',firebaseUid:null});const pages:any={[studentDB]:[{id:k,parent:{database_id:studentDB},properties:{}}],[enrollmentDB]:[{id:other,parent:{database_id:enrollmentDB},properties:{학생:{relation:[{id:k}]}}}]};const calls:any[]=[];const notion:any=async(path:string,method:string,body:any)=>{calls.push({path,method,body});return {results:pages[path.split('/')[1]]||[],has_more:false};};return {...f,pages,calls,notion,actor:{uid:'principal',admin:false,principal:true,academyId:'main'}};}
test('audit is read only, excludes another academy and does not return sensitive fields',async()=>{const f=fixture();f.rows.set('teacherMessages/foreign',{academyId:'other',status:'uncertain',body:'SECRET',recipient:'01012345678'});f.rows.set('reportSlugs/one',{internalStudentId:'internal',studentKey:k,active:true,parentPhonePinHash:'SECRET'});const before=structuredClone([...f.rows]);const r=await readIntegrityAudit(f.db,f.actor,f.notion);assert.equal(r.complete,true);assert.deepEqual(r.issues,[]);assert.deepEqual([...f.rows],before);assert.ok(f.calls.every(c=>c.method==='POST'&&c.path.endsWith('/query')));assert.ok(!JSON.stringify(r).includes('SECRET'));});
test('teachers and unconfigured academies cannot invoke audit or query Notion',async()=>{const f=fixture();await assert.rejects(readIntegrityAudit(f.db,{...f.actor,principal:false},f.notion),/FORBIDDEN/);await assert.rejects(readIntegrityAudit(f.db,{...f.actor,academyId:'other'},f.notion),/NOTION_REGISTRATION_SOURCE_REQUIRED/);assert.equal(f.calls.length,0);});
test('canonical mapping conflicts are surfaced without changing ownership',async()=>{const f=fixture();f.rows.set('notionStudentMappings/legacy',{notionStudentPageId:k.replace(/-/g,''),internalStudentId:'other',firebaseUid:'stale'});const r=await readIntegrityAudit(f.db,f.actor,f.notion);assert.ok(r.issues.some(i=>i.code==='IDENTITY_CONFLICT'));assert.ok(!r.issues.some(i=>i.code==='ACCOUNT_LINK'));});
test('duplicate enrollment and report revisions are exact identity based',async()=>{const f=fixture();f.pages[enrollmentDB].push({...f.pages[enrollmentDB][0],id:k});for(const id of ['a','b'])f.rows.set('lessonReports/'+id,{internalStudentId:'internal',teacherDraftId:'draft',teacherAppRevision:2});f.rows.set('lessonReports/c',{internalStudentId:'internal',teacherDraftId:'draft',teacherAppRevision:3});const r=await readIntegrityAudit(f.db,f.actor,f.notion);assert.equal(r.issues.filter(i=>i.code==='LESSON_REPORT_DUPLICATE').length,1);assert.ok(r.issues.some(i=>i.code==='ENROLLMENT_COUNT'));});
test('source failure marks incomplete and never reports missing rows for that source',async()=>{const f=fixture();const r=await readIntegrityAudit(f.db,f.actor,async(path,method,body)=>{if(path.includes(enrollmentDB))throw Error('secret raw upstream error');return f.notion(path,method,body);});assert.equal(r.complete,false);assert.ok(r.issues.some(i=>i.code==='SOURCE_UNAVAILABLE'));assert.ok(!r.issues.some(i=>i.code==='ENROLLMENT_COUNT'));assert.ok(!JSON.stringify(r).includes('secret'));});
test('pending registration uses syncStatus and preserves completed records',async()=>{const f=fixture();f.rows.set('teacherStudentRegistrations/a',{academyId:'main',syncStatus:'uncertain'});f.rows.set('teacherStudentRegistrations/b',{academyId:'main',syncStatus:'synced'});f.rows.set('teacherMessages/c',{academyId:'main',studentKey:k,status:'uncertain'});const r=await readIntegrityAudit(f.db,f.actor,f.notion);assert.equal(r.issues.filter(i=>i.code==='PENDING_teacherStudentRegistrations').length,1);assert.ok(r.issues.some(i=>i.code==='PENDING_teacherMessages'));});
test('principal sees only membership students even when remote database is shared',async()=>{const f=fixture();f.pages[studentDB].push({id:other,parent:{database_id:studentDB},properties:{}});f.rows.set('notionStudentMappings/foreign',{notionStudentPageId:other,internalStudentId:'foreign',firebaseUid:'absent'});const r=await readIntegrityAudit(f.db,f.actor,f.notion);assert.equal(r.studentCount,1);assert.ok(!r.issues.some(i=>i.studentKey===other));});
test('invalid pagination is incomplete rather than silently truncating',async()=>{const f=fixture();const r=await readIntegrityAudit(f.db,f.actor,async(path,method,body)=>path.includes(enrollmentDB)?{results:f.pages[enrollmentDB],has_more:true,next_cursor:null}:f.notion(path,method,body));assert.equal(r.complete,false);});
test('account mismatch and active report duplicates are flagged without exposing PIN',async()=>{const f=fixture();f.rows.set('users/u',{role:'teacher',notionStudentKey:k});f.rows.set('notionStudentMappings/'+hashStudentKey(k),{notionStudentPageId:k,internalStudentId:'internal',firebaseUid:'u'});for(const id of ['a','b'])f.rows.set('reportSlugs/'+id,{internalStudentId:'internal',studentKey:k,active:true,parentPhonePinHash:'PINSECRET'});const r=await readIntegrityAudit(f.db,f.actor,f.notion);assert.ok(r.issues.some(i=>i.code==='ACCOUNT_LINK'));assert.ok(r.issues.some(i=>i.code==='ACTIVE_REPORT_DUPLICATE'));assert.ok(!JSON.stringify(r).includes('PINSECRET'));});
test('truncated relations are incomplete rather than treated as full connections',async()=>{const f=fixture();f.pages[enrollmentDB][0].properties.학생={type:'relation',relation:[{id:k}],has_more:true};const r=await readIntegrityAudit(f.db,f.actor,f.notion);assert.equal(r.complete,false);assert.ok(!r.issues.some(i=>i.code==='ENROLLMENT_COUNT'));});
test('duplicate Notion markers surface separately from report identities',async()=>{const f=fixture();const id='ab289f5b-1cf5-4160-809e-10d268c9c385';f.pages[id]=['a','b'].map(page=>({id:page,parent:{database_id:id},properties:{학생:{relation:[{id:k}]},'앱 기록 ID':{rich_text:[{plain_text:'draft-id'}]}}}));const r=await readIntegrityAudit(f.db,f.actor,f.notion);assert.equal(r.issues.filter(i=>i.code==='NOTION_LESSON_MARKER_DUPLICATE').length,2);});
