import test from 'node:test';import assert from 'node:assert/strict';
import {syncTeacherAssignments} from '../api/_lib/teacherAssignmentSync.js';
import {assignmentError} from '../src/lib/teacherAssignmentStatus.js';
const t='33333333-3333-4333-8333-333333333333',co='44444444-4444-4444-8444-444444444444',k='11111111-1111-4111-8111-111111111111',e='22222222-2222-4222-8222-222222222222';
const teacherDB='3d274aff-32ce-4a33-870d-2689259113a6',enrollmentDB='3ec0d0f1-c79a-80b2-bb52-ea162888fe9a';
const subjects=['영어','수학','국어','과학','한국사'];
function fixture(){const schema:any={properties:Object.fromEntries(subjects.map(s=>[s+' 담당',{type:'relation',relation:{database_id:teacherDB}}]))};const teacherSchema={properties:{'담당 과목':{type:'multi_select',multi_select:{options:subjects.map(name=>({name}))}}}};
 const pages:any={[t]:{id:t,parent:{database_id:teacherDB},properties:{상태:{select:{name:'재직'}},'담당 과목':{multi_select:[{name:'영어'}]}}},[e]:{id:e,parent:{database_id:enrollmentDB},properties:{학생:{relation:[{id:k}]},...Object.fromEntries(subjects.map(s=>[s+' 담당',{relation:s==='영어'?[{id:t},{id:co}]:[]}]))}}};
 const calls:any[]=[];const notion:any=async(path:string,method='GET',body:any)=>{calls.push({path,method,body});if(path==='databases/'+enrollmentDB)return schema;if(path==='databases/'+teacherDB)return teacherSchema;if(path.endsWith('/query'))return {results:[structuredClone(pages[e])],has_more:false};if(method==='PATCH'){Object.assign(pages[path.split('/')[1]].properties,body.properties);return structuredClone(pages[path.split('/')[1]]);}return structuredClone(pages[path.split('/')[1]]);};return {schema,teacherSchema,pages,calls,notion};}
test('remove only selected teacher, preserve joint teacher and retry without duplicate patches',async()=>{const f=fixture(),old={scopes:[{studentKey:k,subject:'영어'}],notionTeacherPageId:t},next={scopes:[],notionTeacherPageId:t};await syncTeacherAssignments(next,old,f.notion);assert.deepEqual(f.pages[e].properties['영어 담당'].relation,[{id:co}]);const writes=f.calls.filter(c=>c.method==='PATCH').length;await syncTeacherAssignments(next,old,f.notion);assert.equal(f.calls.filter(c=>c.method==='PATCH').length,writes);});
test('preflight fails before all writes with exact schema guidance',async()=>{const f=fixture();f.schema.properties['수학 담당']={type:'rich_text'};await assert.rejects(syncTeacherAssignments({notionTeacherPageId:t,scopes:[]},{},f.notion),/ASSIGNMENT_SCHEMA:DB_수강.수학 담당/);assert.ok(f.calls.every(c=>c.method!=='PATCH'));assert.match(assignmentError('ASSIGNMENT_SCHEMA:DB_수강.수학 담당'),/수학 담당/);});
test('duplicate enrollment or incomplete relations never overwrite assignments',async()=>{const f=fixture();await assert.rejects(syncTeacherAssignments({notionTeacherPageId:t,scopes:[{studentKey:k,subject:'영어'}]},{},async(path,m,b)=>path.endsWith('/query')?{results:[f.pages[e],f.pages[e]]}:f.notion(path,m,b)),/NOTION_ENROLLMENT_REQUIRED/);assert.ok(f.calls.every(c=>c.method!=='PATCH'));});
test('before-write durable marker runs before uncertain remote patch',async()=>{const f=fixture();let durable=false;await assert.rejects(syncTeacherAssignments({notionTeacherPageId:t,scopes:[]},{scopes:[{studentKey:k,subject:'영어'}]},async(path,m,b)=>{if(m==='PATCH'){assert.equal(durable,true);throw Error('NOTION_502');}return f.notion(path,m,b);},async()=>{durable=true;}),/NOTION_502/);assert.equal(durable,true);});
test('on removal fresh remote joint assignments are kept rather than stale query snapshot',async()=>{const f=fixture();const newer='55555555-5555-4555-8555-555555555555';const notion:any=async(path:string,m:string,b:any)=>{if(path==='pages/'+e)f.pages[e].properties['영어 담당'].relation.push({id:newer});return f.notion(path,m,b);};await syncTeacherAssignments({notionTeacherPageId:t,scopes:[]},{scopes:[{studentKey:k,subject:'영어'}]},notion);assert.deepEqual(f.pages[e].properties['영어 담당'].relation,[{id:co},{id:newer}]);});
test('stopped teachers rejected before writes',async()=>{const f=fixture();f.pages[t].properties.상태.select.name='중단';await assert.rejects(syncTeacherAssignments({notionTeacherPageId:t,scopes:[]},{},f.notion),/TEACHER_NOT_CONFIGURED/);assert.ok(f.calls.every(c=>c.method!=='PATCH'));});
