import test from 'node:test';import assert from 'node:assert/strict';
import {archiveTeacherLesson} from '../api/_lib/teacherLessonArchive.js';
import {registrationFirestore} from './helpers/registrationFirestore.js';
import {storeWebhookLessonReport} from '../api/_lib/lessonWebhookProjection.js';
const id='11111111-1111-4111-8111-111111111111',key='22222222-2222-4222-8222-222222222222',page='33333333-3333-4333-8333-333333333333',database='44444444-4444-4444-8444-444444444444';
function fixture(){const f=registrationFirestore(),actor:any={uid:'teacher',admin:false,scopes:[{studentKey:key,subject:'영어'}],teachingScopes:[{studentKey:key,subject:'영어'}]};f.rows.set('teacherLessonDrafts/'+id,{ownerUid:'teacher',revision:1,stage:'report_published_notion_pending',data:{studentKey:key,subject:'영어'},notionWrite:{database,attempted:false,done:false}});f.rows.set('lessonReports/'+id,{teacherDraftId:id,studentKey:key});return {...f,actor};}
test('explicit pending unsent draft can be archived without creating Notion',async()=>{const f=fixture();f.rows.set('lessonReports/keep',{teacherDraftId:'another',studentKey:key});await archiveTeacherLesson(f.db,f.actor,id,1,async(path,method)=>{assert.ok(path.endsWith('/query'));return {results:[],has_more:false};});assert.equal(f.rows.get('teacherLessonDrafts/'+id).archived,true);assert.ok(!f.rows.has('lessonReports/'+id));assert.ok(f.rows.has('lessonReports/keep'));});
test('unknown creation result cannot be blindly discarded',async()=>{const f=fixture();f.rows.get('teacherLessonDrafts/'+id).notionWrite.attempted=true;await assert.rejects(archiveTeacherLesson(f.db,f.actor,id,1,async()=>({results:[],has_more:false})),/NOTION_WRITE_RESULT_UNCERTAIN/);assert.ok(!f.rows.get('teacherLessonDrafts/'+id).archived);assert.ok(f.rows.has('lessonReports/'+id));});
test('recovered remote is archived and late webhook cannot recreate its report',async()=>{const f=fixture();let archived=false;const notion:any=async(path:string,method:string)=>path.endsWith('/query')?{results:[{id:page}]}:method==='PATCH'?(archived=true,{}):{id:page,parent:{database_id:database},archived,properties:{학생:{relation:[{id:key}]},'앱 기록 ID':{rich_text:[{plain_text:id}]}}};await archiveTeacherLesson(f.db,f.actor,id,1,notion);assert.equal(archived,true);const result=await storeWebhookLessonReport(f.db,{notionPageId:page,notionStudentPageId:key,lessonDateStart:'2026-10-05'} as any,{studentKey:key,internalStudentId:'internal'});assert.equal(result.reason,'APP_ARCHIVED');});
test('active publish and wrong owner block all external mutations',async()=>{const f=fixture();let calls=0;const notion:any=async()=>{calls++;return {};};await assert.rejects(archiveTeacherLesson(f.db,{...f.actor,uid:'other'},id,1,notion),/FORBIDDEN/);f.rows.get('teacherLessonDrafts/'+id).notionWrite.leaseUntil=Date.now()+10000;await assert.rejects(archiveTeacherLesson(f.db,f.actor,id,1,notion),/PUBLISH_IN_PROGRESS/);assert.equal(calls,0);});
test('archive response loss resumes selected page without touching another draft',async()=>{const f=fixture();let archived=false,patches=0;const notion:any=async(path:string,method:string)=>{if(path.endsWith('/query'))return {results:archived?[]:[{id:page}]};if(method==='PATCH'){archived=true;patches++;throw Error('NOTION_502');}return {id:page,parent:{database_id:database},archived,properties:{학생:{relation:[{id:key}]},'앱 기록 ID':{rich_text:[{plain_text:id}]}}};};await assert.rejects(archiveTeacherLesson(f.db,f.actor,id,1,notion),/NOTION_502/);assert.equal(f.rows.get('teacherLessonDrafts/'+id).notionPageId,page);await archiveTeacherLesson(f.db,f.actor,id,1,notion);assert.equal(patches,1);assert.equal(f.rows.get('teacherLessonDrafts/'+id).archived,true);});
