import {useEffect,useState} from 'react';
export default function AcademyLessonReview({data,request,act,busy}:{data:any;request:(action?:string,body?:any)=>Promise<any>;act:(f:()=>Promise<any>)=>Promise<void>;busy:boolean}) {
 const [records,setRecords]=useState<any[]>([]),[error,setError]=useState(''),[day,setDay]=useState(''),[student,setStudent]=useState(''),[page,setPage]=useState(1);
 async function load(){const r=await request('read:academy-lessons');setRecords(r.records);setError('');}
 useEffect(()=>{let live=true;request('read:academy-lessons').then(r=>{if(live)setRecords(r.records);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 const visible=records.filter(r=>(!day||r.data.date===day)&&(!student||r.data.studentKey===student)).sort((a,b)=>b.data.date.localeCompare(a.data.date));
 const pages=Math.max(1,Math.ceil(visible.length/10)),current=Math.min(page,pages);
 return <section className="panel"><div className="flex justify-between"><h2>학원 수업 기록 · {visible.length}건</h2><button className="small-button" disabled={busy} onClick={()=>act(load)}>새로고침</button></div><div className="grid grid-cols-2 gap-2 mb-3"><label>수업 날짜<input type="date" value={day} onChange={e=>{setDay(e.target.value);setPage(1);}}/></label><label>학생<select value={student} onChange={e=>{setStudent(e.target.value);setPage(1);}}><option value="">전체 학생</option>{data.students.map((s:any)=><option key={s.studentKey} value={s.studentKey}>{s.studentDisplayName}</option>)}</select></label></div>{error&&<p role="alert" className="text-sm text-rose-600">{error}</p>}
 <div className="overflow-auto"><table className="academy-log-table"><thead><tr>{['날짜·학생','수업 시간 (회차)','자습 시간 (회차)','학습 내용·과제','지각·결석','특이사항'].map(title=><th key={title}>{title}</th>)}</tr></thead><tbody>{visible.slice((current-1)*10,current*10).map(r=><tr key={r.id}><td>{r.data.date}<br/><strong>{data.students.find((s:any)=>s.studentKey===r.data.studentKey)?.studentDisplayName||'학생'}</strong><br/>{r.data.subject} · {r.teacherName}<br/><span className="text-slate-400">{r.stage==='published'?'반영 완료':r.stage==='draft'?'초안':r.stage==='failed'?'반영 실패':'반영 중'}</span></td><td>{r.data.classSession==='없음'?'없는 날':`${r.data.start}–${r.data.end} (${r.data.round??'미입력'})`}</td><td>{r.data.selfStudy==='없음'?'없는 날':r.data.selfStudy==='있음'?`${r.data.selfStudyStart}–${r.data.selfStudyEnd} (${r.data.selfStudyRound??'미입력'})`:'미확인'}</td><td>{r.data.content}{r.data.assignment&&`\n과제: ${r.data.assignment}`}{r.data.note&&`\n피드백: ${r.data.note}`}{r.data.total>0&&`\n단어: ${r.data.correct}/${r.data.total}`}</td><td>{r.data.attendance}{r.data.attendanceNote&&`\n${r.data.attendanceNote}`}</td><td>{r.data.specialNote||'—'}</td></tr>)}</tbody></table></div><div className="review-pagination"><button disabled={current===1} onClick={()=>setPage(current-1)}>이전</button><span>{current} / {pages}</span><button disabled={current===pages} onClick={()=>setPage(current+1)}>다음</button></div>
 </section>;
}
