import {useTeacherPage} from '../../lib/useTeacherPage';
import {useState} from 'react';
export default function AcademyLessonReview({data,request,act,busy,onEdit}:{data:any;request:(action?:string,body?:any)=>Promise<any>;act:(f:()=>Promise<any>)=>Promise<void>;busy:boolean;onEdit?:(record:any)=>void}) {
 const [day,setDay]=useState(''),[student,setStudent]=useState(''),[page,setPage]=useState(1),[teacher,setTeacher]=useState('');
 const {result,loading,error,load}=useTeacherPage(data.uid,'academy-lessons',{page,teacher,day,student},request);
 const visible:any[]=result.records,pages=result.pages,current=result.page;
 return <section className="panel"><div className="flex justify-between"><h2>일지 조회 · {result.total}건</h2><button className="small-button" disabled={busy} onClick={()=>act(()=>load(true))}>새로고침</button></div><div className="workspace-filters mb-3">{(data.admin||data.principal)&&<label>작성자 선생님<select value={teacher} onChange={e=>{setTeacher(e.target.value);setPage(1);}}><option value="">전체 선생님</option>{(result.teachers||[]).map(({uid,name}:any)=><option key={uid} value={uid}>{name}</option>)}</select></label>}<label>수업 날짜<input type="date" value={day} onChange={e=>{setDay(e.target.value);setPage(1);}}/></label><label>학생<select value={student} onChange={e=>{setStudent(e.target.value);setPage(1);}}><option value="">전체 학생</option>{data.students.map((s:any)=><option key={s.studentKey} value={s.studentKey}>{s.studentDisplayName}</option>)}</select></label></div>{error&&<p role="alert" className="text-sm text-rose-600">{error}</p>}
 {loading&&<p role="status" className="text-sm text-slate-500 py-3">일지 기록을 불러오는 중…</p>}<div className="overflow-auto"><table className="academy-log-table"><thead><tr>{['날짜·학생','수업 시간 (회차)','자습 시간 (회차)','학습 내용·과제','지각·결석','특이사항'].map(title=><th key={title}>{title}</th>)}</tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{r.data.date}<br/><strong>{data.students.find((s:any)=>s.studentKey===r.data.studentKey)?.studentDisplayName||'학생'}</strong><br/>{r.data.subject} · {r.teacherName}<br/><span className="text-slate-400">{r.stage==='published'?'반영 완료':r.stage==='draft'?'초안':r.stage==='failed'?'반영 실패':'반영 중'}</span></td><td>{r.data.classSession==='없음'?'없는 날':`${r.data.start}–${r.data.end} (${r.data.round??'미입력'})`}</td><td>{r.data.selfStudy==='없음'?'없는 날':r.data.selfStudy==='있음'?`${r.data.selfStudyStart}–${r.data.selfStudyEnd} (${r.data.selfStudyRound??'미입력'})`:'미확인'}</td><td>{r.data.content}{r.data.assignment&&`\n과제: ${r.data.assignment}`}{r.data.note&&`\n피드백: ${r.data.note}`}{r.data.total>0&&`\n일반 테스트: ${r.data.correct}/${r.data.total}`}{r.data.examTotal>0&&`\n내신 대비 테스트: ${r.data.examCorrect}/${r.data.examTotal}`}<br/>{onEdit&&(data.admin||r.ownerUid===data.uid)&&<button className="small-button" disabled={busy} onClick={()=>act(async()=>{const record=r.source==='notion'?(await request('import-source-record',{id:r.id,kind:'lesson'})).record:r;onEdit(record);})}>일지 수정</button>}</td><td>{r.data.attendance}{r.data.attendanceNote&&`\n${r.data.attendanceNote}`}</td><td>{r.data.specialNote||'—'}</td></tr>)}</tbody></table></div><div className="review-pagination"><button disabled={loading||current===1} onClick={()=>setPage(current-1)}>이전</button><span>{current} / {pages}</span><button disabled={loading||current===pages} onClick={()=>setPage(current+1)}>다음</button></div>
 </section>;
}
