import {useEffect,useRef,useState} from 'react';
import {onAuthStateChanged} from 'firebase/auth';
import {auth} from '../../lib/firebase';
import WorkspaceDialog from './WorkspaceDialog';
export default function LessonConflictReview({record,request,act,busy,refresh}:{key?:string;record:any;request:any;act:any;busy:boolean;refresh:()=>Promise<any>}){
 const [review,setReview]=useState<any>(null),[choice,setChoice]=useState<'app'|'notion'>('app'),[confirmed,setConfirmed]=useState(false);
 const generation=useRef(0);useEffect(()=>{const stop=onAuthStateChanged(auth,()=>{generation.current++;setReview(null);setConfirmed(false);});return()=>{generation.current++;stop();};},[]);
 if(record.failureCode!=='NOTION_EDIT_CONFLICT'||record.archived)return null;
 return <><button className="small-button mt-2" disabled={busy} onClick={()=>void act(async()=>{const token=generation.current,uid=auth.currentUser?.uid;const result=await request('read:lesson-conflict',{id:record.id});if(token!==generation.current||auth.currentUser?.uid!==uid)return;setReview(result);setConfirmed(false);setChoice('app');})}>앱·노션 내용 비교해서 해결</button><WorkspaceDialog open={Boolean(review)} title="일지 저장 충돌 해결" onClose={()=>{if(!busy)setReview(null);}}>{review&&<><p>{review.date} · {review.subject}</p><p className="text-sm mt-2">아래 내용을 비교하고 유지할 내용을 선택하세요. 같은 노션 일지에 반영하며 학생·학부모 리포트도 선택한 내용으로 갱신합니다.</p><div className="overflow-auto mt-3"><table><thead><tr><th>항목</th><th>앱 저장 요청</th><th>현재 노션</th></tr></thead><tbody>{review.fields.map((f:any)=><tr key={f.name}><td>{f.name}</td><td className="whitespace-pre-wrap p-2">{String(f.app)}</td><td className="whitespace-pre-wrap p-2">{String(f.notion)}</td></tr>)}</tbody></table></div><label className="block mt-3"><input type="radio" checked={choice==='app'} onChange={()=>{setChoice('app');setConfirmed(false);}}/> 앱 내용을 유지</label><label className="block mt-2"><input type="radio" disabled={!review.canUseNotion} checked={choice==='notion'} onChange={()=>{setChoice('notion');setConfirmed(false);}}/> 현재 노션 내용을 유지</label>{!review.canUseNotion&&<p className="text-sm">노션 기록의 필수 항목 또는 점수·시간이 앱 입력 기준과 맞지 않아 선택할 수 없습니다. 앱 내용을 선택하거나 노션을 수정한 뒤 비교 화면을 다시 여세요.</p>}<label className="block mt-3"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> 선택한 내용으로 같은 일지와 리포트를 갱신하는 것을 확인했습니다.</label><button className="primary-button mt-3" disabled={busy||!confirmed} onClick={()=>void act(async()=>{try{const saved=await request('resolve-lesson-conflict',{id:review.id,revision:review.revision,token:review.token,choice});setReview(null);await request('publish',{id:saved.id});}finally{await refresh();}})}>선택한 내용으로 반영</button></>}</WorkspaceDialog></>;
}
