import {useState} from 'react';
import {Pencil,Search} from 'lucide-react';
import {filterScheduleClasses} from '../../lib/schedulePresentation';
import {ClassStatus,SyncStatus} from './ScheduleStatus';
const days=['일','월','화','수','목','금','토'];
export default function ScheduleClassCards({classes,students,onOpen,selectedId,hidden}:{classes:any[];students:any[];onOpen:(c:any)=>void;selectedId:string|null;hidden:boolean}){
 const [query,setQuery]=useState(''),[status,setStatus]=useState('');
 const visible=filterScheduleClasses(classes,students,query,status);
 return <section className="panel schedule-class-list schedule-class-panel" hidden={hidden}><h2 className="sr-only">반 관리</h2><div className="schedule-class-toolbar"><label className="schedule-class-search"><Search size={16}/><input aria-label="반 이름·학생 이름 검색" placeholder="반 이름·학생 이름 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="lesson-mode-switch" role="group" aria-label="반 상태 필터">{[['','전체'],['진행 중','진행 중'],['중단','중단']].map(([key,label])=><button type="button" key={key} aria-pressed={status===key} onClick={()=>setStatus(key)}>{label}</button>)}</div><span>{visible.length}개</span></div><div className="schedule-class-grid">{visible.map(c=><button key={c.id} type="button" className={`schedule-class-open${c.status==='중단'?' is-stopped':''}`} aria-pressed={selectedId===c.id} onClick={()=>onOpen(c)}><span className="schedule-class-title"><strong>{c.name}</strong><ClassStatus value={c.status}/><SyncStatus value={c.notionSyncStage}/><Pencil size={14} aria-hidden="true"/></span><span className="schedule-class-meta"><span>{c.subject}</span><span>{c.students.length}명</span><span>교재 {(c.books||[]).length}권</span></span><span className="schedule-class-times">{c.slots?.length?[...c.slots].sort((a,b)=>[1,2,3,4,5,6,0].indexOf(a.weekday)-[1,2,3,4,5,6,0].indexOf(b.weekday)||a.start.localeCompare(b.start)).map((slot,i)=><span key={slot.id||i}><span className="schedule-weekday-chip">{days[slot.weekday]}</span>{slot.start}–{slot.end}<ClassStatus value={slot.status||c.status}/></span>):'정규 시간 미등록'}</span></button>)}</div>{!visible.length&&<p className="schedule-empty-day">조건에 맞는 반이 없어요</p>}</section>;
}
