import {useId} from 'react';
import {type AdmissionInput} from '../../lib/studentAdmission';
import OptionalMark from './OptionalMark';
export default function StudentAdmissionFields({value,onChange}:{value:AdmissionInput;onChange:(next:AdmissionInput)=>void}){
 const id=useId();const set=(key:keyof AdmissionInput,v:any)=>onChange({...value,[key]:v});
 const input=(key:keyof AdmissionInput,label:string,type='text')=><label key={key} className="block">{label}<OptionalMark/><input id={`${id}-${key}`} type={type} maxLength={key==='address'?500:200} value={String(value[key])} onChange={e=>set(key,e.target.value)}/></label>;
 const area=(key:keyof AdmissionInput,label:string,max=3000)=><label key={key} className="block">{label}<OptionalMark/><textarea rows={3} maxLength={max} value={String(value[key])} onChange={e=>set(key,e.target.value)}/></label>;
 return <details className="mt-5 rounded-xl border border-pink-100 p-3"><summary className="font-bold text-sm cursor-pointer">입학 원서·상담 정보 <OptionalMark/></summary>
 <p className="text-xs text-slate-500 my-3">기본 정보만으로 초안을 저장할 수 있습니다. 상담 정보는 노션 반영 전에 입력해 주세요. 공개 리포트에는 표시하지 않습니다.</p>
 <div className="grid sm:grid-cols-2 gap-3">{input('birthDate','생년월일','date')}{input('referral','알게 된 경로')}{input('address','주소')}{input('previousPeriod','이전 학습 기간')}{input('previousAcademy','이전 학원명')}{area('previousBooks','사용 교재',2000)}{area('previousContent','이전 학습 내용')}</div>
 <fieldset className="mt-4"><legend className="font-bold text-sm">입학 당시 현재 수준 <OptionalMark/></legend><p className="text-xs text-slate-500 my-2">참고 수준 기록입니다. 성적 그래프에 자동 등록하지 않습니다. 미입력은 0점과 구분합니다.</p>
 <div className="space-y-3">{value.levels.map((r,index)=><fieldset key={r.subject} className="border border-pink-100 rounded-xl p-3"><legend>{r.subject}</legend><div className="grid grid-cols-2 gap-2">{([['schoolScore','내신 점수'],['schoolGrade','내신 등급'],['mockScore','모평 점수'],['mockGrade','모평 등급'],['diagnostic','진단평가 결과']] as const).map(([key,label])=><label key={key}>{label}<OptionalMark/><input aria-label={`${r.subject} ${label}`} type={key.endsWith('Score')?'number':'text'} min={key.endsWith('Score')?0:undefined} max={key.endsWith('Score')?100:undefined} step="any" maxLength={key==='diagnostic'?1000:30} value={r[key]??''} onChange={e=>set('levels',value.levels.map((row,i)=>i===index?{...row,[key]:key.endsWith('Score')?(e.target.value===''?null:Number(e.target.value)):e.target.value}:row))}/></label>)}</div></fieldset>)}</div></fieldset>
 <div className="grid sm:grid-cols-2 gap-3 mt-4">{area('goal','학습 목표')}<fieldset><legend className="text-sm">가능한 요일 <OptionalMark/></legend><div className="flex flex-wrap gap-3">{['월','화','수','목','금','토','일'].map(day=><label key={day}><input type="checkbox" checked={value.availableDays.includes(day)} onChange={e=>set('availableDays',e.target.checked?[...value.availableDays,day]:value.availableDays.filter(d=>d!==day))}/> {day}</label>)}</div>{area('availableTimes','가능 시간',1000)}</fieldset>{area('notes','참고 사항',5000)}</div>
 <fieldset className="mt-4"><legend className="font-bold text-sm">원서 동의·서명 확인</legend><p className="text-xs text-slate-500 my-2">원서에서 확인한 상태를 기록합니다. 아래 체크는 원본 서명을 대신하지 않습니다.</p><div className="grid sm:grid-cols-2 gap-3"><label>동의 상태<select value={value.consent} onChange={e=>set('consent',e.target.value)}><option>미확인</option><option>동의</option><option>미동의</option></select></label>{input('consentDate','확인일','date')}{input('signerName','서명자 이름')}<label><input type="checkbox" checked={value.signedPaper} onChange={e=>set('signedPaper',e.target.checked)}/> 서명한 원서 보관 확인</label></div></fieldset>
 </details>;
}
