import {useId} from 'react';
import {admissionSubjects,type AdmissionInput} from '../../lib/studentAdmission';
import OptionalMark from './OptionalMark';
export default function StudentAdmissionFields({value,onChange,section='all'}:{value:AdmissionInput;onChange:(next:AdmissionInput)=>void;section?:'basic'|'learning'|'consent'|'all'}){
 const id=useId();const set=(key:keyof AdmissionInput,v:any)=>onChange({...value,[key]:v});
 const input=(key:keyof AdmissionInput,label:string,type='text')=><label key={key} className="block">{label}<OptionalMark/><input id={`${id}-${key}`} type={type} maxLength={key==='address'?500:key==='signerName'?100:200} value={String(value[key])} onChange={e=>set(key,e.target.value)}/></label>;
 const area=(key:keyof AdmissionInput,label:string,max=3000)=><label key={key} className="block">{label}<OptionalMark/><textarea rows={3} maxLength={max} value={String(value[key])} onChange={e=>set(key,e.target.value)}/></label>;
 function level(subject:typeof admissionSubjects[number],key:string,v:any){const existing=value.levels.find(r=>r.subject===subject)||{subject,schoolScore:null,schoolGrade:'',mockScore:null,mockGrade:'',diagnostic:''};set('levels',[...value.levels.filter(r=>r.subject!==subject),{...existing,[key]:v}]);}
 return <>
 {(section==='basic'||section==='all')&&<div className="grid sm:grid-cols-2 gap-3 sm:col-span-2">{input('birthDate','생년월일','date')}{input('referral','알게 된 경로')}<div className="sm:col-span-2">{input('address','주소')}</div></div>}
 {(section==='learning'||section==='all')&&<section className="admission-section"><h3>학습 수준·상담 내용</h3><div className="grid sm:grid-cols-2 gap-3">{input('previousPeriod','이전 학습 기간')}{input('previousAcademy','이전 학원명')}{area('previousBooks','사용 교재',2000)}{area('previousContent','이전 학습 내용')}</div>
 <div className="mt-4 overflow-x-auto"><table className="admission-level-table"><caption>입학 당시 현재 수준 <OptionalMark/></caption><thead><tr><th scope="col">평가 항목</th>{admissionSubjects.map(subject=><th scope="col" key={subject}>{subject}</th>)}</tr></thead><tbody>{([['schoolScore','내신 점수'],['schoolGrade','내신 등급'],['mockScore','모평 점수'],['mockGrade','모평 등급'],['diagnostic','진단평가 결과']] as const).map(([key,label])=><tr key={key}><th scope="row">{label}</th>{admissionSubjects.map(subject=>{const row=value.levels.find(r=>r.subject===subject);return <td key={subject}><input aria-label={`${subject} ${label}`} type={key.endsWith('Score')?'number':'text'} min={key.endsWith('Score')?0:undefined} max={key.endsWith('Score')?100:undefined} step="any" maxLength={key==='diagnostic'?1000:30} value={row?.[key]??''} onChange={e=>level(subject,key,key.endsWith('Score')?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/></td>;})}</tr>)}</tbody></table></div>
 <p className="text-xs text-slate-500 mt-2">미입력은 0점과 구분하며, 성적 그래프에는 자동 등록하지 않습니다.</p>
 <div className="grid sm:grid-cols-2 gap-3 mt-4">{area('goal','학습 목표')}<fieldset><legend className="text-sm">수업 가능 요일 <OptionalMark/></legend><div className="flex flex-wrap gap-3 py-2">{['월','화','수','목','금','토','일'].map(day=><label key={day}><input type="checkbox" checked={value.availableDays.includes(day)} onChange={e=>set('availableDays',e.target.checked?[...value.availableDays,day]:value.availableDays.filter(d=>d!==day))}/> {day}</label>)}</div>{area('availableTimes','수업 가능 시간',1000)}</fieldset><div className="sm:col-span-2">{area('notes','상담 참고 사항',5000)}</div></div></section>}
 {(section==='consent'||section==='all')&&<section className="admission-section"><h3>원서 동의·서명 확인</h3><p className="text-xs text-slate-500 mb-3">원서에서 확인한 상태를 기록합니다. 아래 체크는 원본 서명을 대신하지 않습니다.</p><div className="grid sm:grid-cols-2 gap-3"><label>개인정보 동의<select value={value.consent} onChange={e=>set('consent',e.target.value)}><option>미확인</option><option>동의</option><option>미동의</option></select></label>{input('consentDate','동의 확인일','date')}{input('signerName','서명자 이름')}<label className="flex items-center gap-2"><input type="checkbox" checked={value.signedPaper} onChange={e=>set('signedPaper',e.target.checked)}/> 서명한 원서 보관 확인</label></div></section>}
 </>;
}
