import {useEffect,useState} from 'react';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(new Date());
const blank=()=>({studentKey:'',subject:'영어',examType:'학교 내신',title:'',examDate:today(),deadline:null as string|null,score:null as number|null,maxScore:100 as number|null,grade:'',submissionStatus:'제출 완료',note:''});
export default function TeacherAcademicManager({data,busy,request,act}:{data:any;busy:boolean;request:(action?:string,body?:any)=>Promise<any>;act:(f:()=>Promise<any>)=>Promise<void>}) {
 const [records,setRecords]=useState<any[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState('');
 const [value,setValue]=useState<any>(()=>({...blank(),subject:data.scopes?.[0]?.subject||'영어'})),[selected,setSelected]=useState<any>(null),[saved,setSaved]=useState<any>(null);
 const [teacher,setTeacher]=useState(''),[student,setStudent]=useState(''),[kind,setKind]=useState(''),[subject,setSubject]=useState(''),[page,setPage]=useState(1);
 async function load(){const result=await request('read:academic-records');setRecords(result.records);setLoaded(true);setError('');return result.records;}
 useEffect(()=>{let live=true; request('read:academic-records').then(r=>{if(live){setRecords(r.records);setLoaded(true);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 function field(key:string,v:any){setValue((old:any)=>({...old,[key]:v}));}
 const visible=records.filter(r=>(!teacher||r.ownerUid===teacher||r.teacherUids?.includes(teacher))&&(!student||r.data.studentKey===student)&&(!kind||r.data.examType===kind)&&(!subject||r.data.subject===subject)).sort((a,b)=>b.data.examDate.localeCompare(a.data.examDate));
 const pages=Math.max(1,Math.ceil(visible.length/10)),current=Math.min(page,pages);
 const writableStudents=data.students.filter((s:any)=>data.admin||(data.principal?data.teachingScopes||[]:data.scopes).some((scope:any)=>scope.studentKey===s.studentKey));
 const canWrite=!data.principal||writableStudents.length>0;
 const changed=JSON.stringify(saved)!==JSON.stringify(value);
 return <div className={`grid ${canWrite?'lg:grid-cols-[340px_1fr]':''} gap-4`}>
 {canWrite&&<section className="panel"><h2>성적 입력</h2><fieldset disabled={busy}>
 <div className="grid grid-cols-2 gap-2"><label>학생<select value={value.studentKey} onChange={e=>field('studentKey',e.target.value)}><option value="">학생 선택</option>{writableStudents.map((s:any)=><option key={s.studentKey} value={s.studentKey}>{s.studentDisplayName}</option>)}</select></label><label>과목<select value={value.subject} onChange={e=>field('subject',e.target.value)}>{['영어','수학','국어','과학','한국사'].filter(subject=>data.admin||(data.principal?data.teachingScopes||[]:data.scopes).some((s:any)=>s.subject===subject&&(!value.studentKey||s.studentKey===value.studentKey))).map(s=><option key={s}>{s}</option>)}</select></label>
 <label>시험 종류<select value={value.examType} onChange={e=>field('examType',e.target.value)}><option>학교 내신</option><option>학력평가</option></select></label><label>시험일<input type="date" required value={value.examDate} onChange={e=>field('examDate',e.target.value)}/></label></div>
 <label className="block mt-2">시험명<input value={value.title} onChange={e=>field('title',e.target.value)} placeholder="예: 2학기 중간고사"/></label>
 <div className="grid grid-cols-2 gap-2 mt-2"><label>제출 상태<select value={value.submissionStatus} onChange={e=>setValue((v:any)=>({...v,submissionStatus:e.target.value,score:e.target.value==='제출 완료'?v.score:null}))}><option>제출 완료</option><option>미제출</option><option>제출 대상 아님</option></select></label><label>예상 등급<input value={value.grade} onChange={e=>field('grade',e.target.value)} placeholder="숫자 또는 A/B"/></label>{[['score','원점수'],['maxScore','만점']].map(([key,label])=><label key={key}>{label}<input type="number" step="any" min={key==='score'?0:0.01} disabled={key==='score'&&value.submissionStatus!=='제출 완료'} value={value[key]??''} onChange={e=>field(key,e.target.value===''?null:Number(e.target.value))}/></label>)}
 <label>제출 기한 · 선택<input type="date" value={value.deadline||''} onChange={e=>field('deadline',e.target.value||null)}/></label></div>
 <label className="block mt-2">비고<textarea rows={2} value={value.note} onChange={e=>field('note',e.target.value)}/></label>
 <div className="flex flex-wrap gap-2 mt-3"><button className="primary-button" onClick={()=>act(async()=>{const result=await request('save-academic',{id:selected?.id,revision:selected?.revision,notionPageId:selected?.source==='notion'?selected.notionPageId:undefined,data:value});const fresh=await load();const record=fresh.find((r:any)=>r.id===result.id);setSelected(record);setSaved(record.data);setValue(record.data);})}>저장</button><button className="small-button" disabled={!selected?.revision||changed||['published','publishing','notion_saved'].includes(selected?.stage)} onClick={()=>act(async()=>{await request('publish-academic',{id:selected.id});const fresh=await load();setSelected(fresh.find((r:any)=>r.id===selected.id));})}>반영</button><button className="small-button" onClick={()=>{setSelected(null);setSaved(null);setValue(blank());}}>새 성적</button></div>
 <p className="text-xs text-slate-500 mt-2">저장은 초안 보관, 반영은 Notion과 학생·학부모 성적에 적용합니다.</p>{selected&&<p role="status" className="text-xs text-slate-500 mt-2">{({draft:'저장됨',published:'반영 완료',failed:'반영 실패',notion_saved:'Notion 저장됨',publishing:'반영 중'} as any)[selected.stage]}</p>}
 </fieldset></section>}
 <section className="panel"><div className="flex justify-between gap-2"><h2>성적 기록 · {visible.length}건</h2><button className="small-button" disabled={busy} onClick={()=>act(load)}>새로고침</button></div>
 <div className="workspace-filters mb-3">{(data.admin||data.principal)&&<label>담당 선생님<select aria-label="성적 선생님 필터" value={teacher} onChange={e=>{setTeacher(e.target.value);setPage(1);}}><option value="">전체 선생님</option>{[...new Set(records.flatMap(r=>r.teacherUids?.length?r.teacherUids:[r.ownerUid]).filter(Boolean))].map(uid=><option key={uid} value={uid}>{data.staff?.find((s:any)=>s.uid===uid)?.name || (uid===data.uid?'나':'연결되지 않은 작성자')}</option>)}</select></label>}<label>학생<select aria-label="학생 필터" value={student} onChange={e=>{setStudent(e.target.value);setPage(1);}}><option value="">전체 학생</option>{data.students.map((s:any)=><option key={s.studentKey} value={s.studentKey}>{s.studentDisplayName}</option>)}</select></label><label>시험 종류<select aria-label="시험 종류 필터" value={kind} onChange={e=>{setKind(e.target.value);setPage(1);}}><option value="">전체 시험</option><option>학교 내신</option><option>학력평가</option></select></label><label>과목<select aria-label="과목 필터" value={subject} onChange={e=>{setSubject(e.target.value);setPage(1);}}><option value="">전체 과목</option>{['영어','수학','국어','과학','한국사'].map(s=><option key={s}>{s}</option>)}</select></label></div>
 {error&&<p role="alert" className="text-sm text-rose-600">{error}</p>}{!loaded&&!error&&<p className="text-sm text-slate-500">성적을 불러오는 중…</p>}
 {visible.slice((current-1)*10,current*10).map(r=><div key={r.id} className="border-b border-slate-100 py-3 text-sm"><div className="flex justify-between gap-2"><strong>{data.students.find((s:any)=>s.studentKey===r.data.studentKey)?.studentDisplayName||'학생'} · {r.data.title}</strong><span>{r.data.submissionStatus==='제출 완료'&&r.data.score!==null?`${r.data.score} / ${r.data.maxScore??'—'}`:r.data.submissionStatus}</span></div><p className="text-xs text-slate-500 mt-1">{r.data.examDate} · {r.data.subject} · {r.data.examType}{r.data.grade?` · 등급 ${r.data.grade}`:''} · {r.stage==='published'?'반영 완료':r.stage==='draft'?'저장됨':r.stage==='failed'?'반영 실패':'반영 중'}</p>{r.data.note&&<p className="text-xs text-slate-600 mt-1 whitespace-pre-wrap">{r.data.note}</p>}{canWrite&&(data.admin||r.ownerUid===data.uid||r.source==='notion')&&<button className="small-button mt-2" onClick={()=>{setSelected(r);setSaved(r.source==='notion'?null:r.data);setValue(r.data);}}>열기</button>}</div>)}
 {loaded&&!visible.length&&<p className="text-sm text-slate-500 py-3">해당하는 성적이 없습니다.</p>}<div className="review-pagination"><button disabled={current===1} onClick={()=>setPage(current-1)}>이전</button><span>{current} / {pages}</span><button disabled={current===pages} onClick={()=>setPage(current+1)}>다음</button></div></section>
 </div>;
}
