import {useEffect,useRef,useState} from 'react';
import {onAuthStateChanged} from 'firebase/auth';
import {auth} from '../../lib/firebase';
import {teacherAuthenticatedRequest} from '../../lib/teacherAuthenticatedRequest';
import {messageVariables,renderTeacherMessage,unresolvedMessage} from '../../lib/teacherMessage';
import WorkspaceDialog from './WorkspaceDialog';
const labels:Record<string,string>={prepared:'노션 저장 대기',ready:'발송 전',sending:'발송 요청 중 · 결과 확인 필요',accepted:'발송 요청 접수',uncertain:'발송 결과 불명확 · 자동 재전송 차단'};
export default function TeacherMessageComposer({studentKey,subjects,onClose}:{studentKey:string;subjects:string[];onClose:()=>void}){
 const [subject,setSubject]=useState(subjects[0]||'영어'),[data,setData]=useState<any>(null),[templateId,setTemplateId]=useState(''),[lessonId,setLessonId]=useState(''),[body,setBody]=useState(''),[record,setRecord]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(false);
 const version=useRef(0),working=useRef(false),intent=useRef<any>(null);
 async function request(action:string,values:any={},read=false){const q=new URLSearchParams({action,...values});const r=await teacherAuthenticatedRequest<any>(auth,read?`/api/teacher/workspace?${q}`:'/api/teacher/workspace',read?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...values})});if(!r.ok||!r.data?.ok)throw Error(r.data?.message||'결과를 확인하지 못했습니다. 목록에서 저장한 요청을 확인해 주세요.');return r.data;}
 useEffect(()=>{++version.current;let live=true;setData(null);setRecord(null);setBody('');intent.current=null;setTemplateId('');setLessonId('');setConfirmed(false);setMessage('');const initialUid=auth.currentUser?.uid;const unsub=onAuthStateChanged(auth,user=>{if(user?.uid!==initialUid){version.current++;setData(null);setRecord(null);setMessage('로그인 계정이 변경되었습니다. 창을 다시 열어 주세요.');}});const generation=version.current;void request('messages',{studentKey,subject},true).then(r=>{if(live&&version.current===generation)setData(r);}).catch(e=>{if(live)setMessage(e.message);});return()=>{live=false;version.current++;unsub();};},[studentKey,subject]);
 function generate(){const template=data?.templates.find((t:any)=>t.id===templateId),lesson=data?.lessons.find((l:any)=>l.id===lessonId);if(!template)return;const r=renderTeacherMessage(template.body,messageVariables(data.profile,lesson?.data));setBody(r.body);setMessage(r.missing.length?`확인할 변수: ${r.missing.join(', ')}`:'본문을 확인하고 필요한 내용을 수정해 주세요.');setConfirmed(false);}
 async function run(send=false){if(working.current)return;const generation=version.current,uid=auth.currentUser?.uid;working.current=true;setBusy(true);setMessage('');try{if(send){const r=await request('send-message',{id:record.id,confirmed:true});if(generation!==version.current||auth.currentUser?.uid!==uid)return;setRecord(r.record);setConfirmed(false);setMessage(labels[r.record.status]);}else{const v=intent.current||{id:crypto.randomUUID(),studentKey,subject,templateId,lessonId:lessonId||null,body};intent.current=v;const r=await request('prepare-message',v);if(generation!==version.current||auth.currentUser?.uid!==uid)return;setRecord(r.record);setMessage('본문을 저장했습니다. 수신자와 본문을 최종 확인해 주세요.');}}catch(e){if(generation===version.current)setMessage(e instanceof Error?e.message:'결과 확인 필요');}finally{working.current=false;if(generation===version.current)setBusy(false);}}
 function close(){if(working.current)return;if(body.trim()&&!record&&!intent.current&&!window.confirm('저장하지 않은 문자본문을 닫을까요?'))return;onClose();}
 return <WorkspaceDialog open title="보호자 문자" onClose={close}>
 <p className="text-xs text-slate-500 mb-3">수업일지 반영과 별도로 발송합니다. 단체 유형 템플릿도 선택한 학생 한 명에게 보냅니다.</p>
 <label>과목 <select value={subject} disabled={busy} onChange={e=>setSubject(e.target.value)}>{subjects.map(s=><option key={s}>{s}</option>)}</select></label>
 {data&&<><div className="space-y-3 my-3"><label className="block">템플릿 <select disabled={Boolean(record)||Boolean(intent.current)||busy} value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">선택</option>{data.templates.map((t:any)=><option key={t.id} value={t.id}>{t.title} · {t.target}</option>)}</select></label>
 <label className="block">반영된 수업일지 <select disabled={Boolean(record)||Boolean(intent.current)||busy} value={lessonId} onChange={e=>setLessonId(e.target.value)}><option value="">수업일지 없이 작성</option>{data.lessons.map((l:any)=><option key={l.id} value={l.id}>{l.data.date} · {l.data.subject}</option>)}</select></label>
 <button className="small-button" disabled={!templateId||busy||Boolean(record)||Boolean(intent.current)} onClick={generate}>템플릿으로 본문 생성</button>
 <label className="block">문자본문<textarea className="w-full mt-2 min-h-64" maxLength={5000} value={record?.body??body} disabled={Boolean(record)||Boolean(intent.current)||busy} onChange={e=>{setBody(e.target.value);setConfirmed(false);}}/></label>
 <p className="text-sm">수신자: {record?.recipient??data.profile.guardianPhone} · {data.profile.displayName} 보호자</p>
 {!record&&<button className="primary-button" disabled={busy||!templateId||!body.trim()||unresolvedMessage(body)} onClick={()=>void run()}>{intent.current?'저장 결과 확인 · 재시도':'본문 저장 · 발송 준비'}</button>}
 {record&&<><p role="status">{labels[record.status]}</p>{record.status==='prepared'&&<button className="small-button" disabled={busy} onClick={()=>{intent.current={id:record.id,studentKey,subject:record.subject,templateId:record.templateId,lessonId:record.lessonId||null,body:record.body};void run();}}>노션 저장 결과 확인 · 재시도</button>}{record.status==='ready'&&<><label className="block"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/> 위 수신자 번호와 문자본문을 최종 확인했습니다.</label><button className="primary-button" disabled={busy||!confirmed} onClick={()=>void run(true)}>확인한 문자 발송</button></>}</>}
 <details><summary>저장·발송 이력</summary>{data.records.map((r:any)=><button key={r.id} disabled={busy} className="small-button block my-2" onClick={()=>{setRecord(r);setConfirmed(false);setBody(r.body);intent.current=null;}}>{new Date(r.createdAt).toLocaleString('ko-KR')} · {labels[r.status]}</button>)}</details>
 </div></>}{!data&&!message&&<p>문자 정보를 불러오는 중…</p>}{message&&<p role="status" className="text-sm text-rose-600">{message}</p>}
 </WorkspaceDialog>;
}
