import ScheduleActionBar from './ScheduleActionBar';
import ChipGroup from './ChipGroup';
import {Check,Trash2,MoreHorizontal} from 'lucide-react';
import {matchesKoreanSearch} from '../../lib/koreanSearch';
import WeekBoard from './WeekBoard';
import ScheduleEventCard from './ScheduleEventCard';
import ScheduleClassCards from './ScheduleClassCards';
import {koreanDay} from '../../lib/teacherWeekCalendar';
import OptionalMark from './OptionalMark';
import WorkspaceDialog from './WorkspaceDialog';
import {useState,type RefObject} from 'react';
const statuses=['대기','진행 중','중단'];
const subjects=['영어','수학','국어','과학','한국사'];
const weekdays=[1,2,3,4,5,6,0];
const dayNames=['일','월','화','수','목','금','토'];
const blank=()=>({name:'',status:'진행 중',subject:'영어',students:[] as string[],slots:[] as any[],books:[] as any[]});
export default function TeacherClassManager({data,busy,request,refresh,act,mode,active=true,view='regular',createRef}:{view?:'dated'|'regular'|'classes';createRef?:RefObject<(()=>void)|null>;active?:boolean;data:any;busy:boolean;request:(a:string,b?:any)=>Promise<any>;refresh:()=>Promise<void>;act:(f:()=>Promise<any>)=>Promise<void>;mode:'schedule'|'curriculum'}) {
 const [form,setForm]=useState(blank),[id,setId]=useState<string|null>(null),[group,setGroup]=useState('active'),[search,setSearch]=useState(''),[notice,setNotice]=useState(''),[classRevision,setClassRevision]=useState(0),[planRevision,setPlanRevision]=useState(0);
 const [classBaseline,setClassBaseline]=useState(()=>JSON.stringify(blank())),[classWorking,setClassWorking]=useState(false);
 const [stopSlot,setStopSlot]=useState<number|null>(null);
 const [editorOpen,setEditorOpen]=useState(false),[planPage,setPlanPage]=useState(1),[planEditorOpen,setPlanEditorOpen]=useState(false);
 const [plan,setPlan]=useState({title:'',subject:'영어',content:'',classId:''}),[planId,setPlanId]=useState<string|null>(null);
 const classes=data.classes||[], own=(r:any)=>data.admin||r.ownerUid===data.uid;
 const eligible=data.students.filter((s:any)=>data.admin||(data.teachingScopes||data.scopes).some((x:any)=>x.studentKey===s.studentKey&&x.subject===form.subject));
 const current=(s:any)=>s.subjects?.length?s.subjects.some((x:any)=>x.subject===form.subject&&x.status==='등록'):s.enrollmentStatus==='등록';
 const visible=eligible.filter((s:any)=>(group==='active'?current(s):!current(s))&&matchesKoreanSearch(s.studentDisplayName,search));
 const open=(c:any)=>{if(busy)return;setClassBaseline(JSON.stringify({name:c.name,status:c.status||'진행 중',subject:c.subject,students:c.students||[],slots:c.slots||[],books:c.books||[]}));setId(c.id);setClassRevision(c.revision||0);setStopSlot(null);setForm({name:c.name,status:c.status||'진행 중',subject:c.subject,students:c.students||[],slots:c.slots||[],books:c.books||[]});setNotice('');setEditorOpen(true);};
 const visiblePlans=data.curricula||[],planPages=Math.max(1,Math.ceil(visiblePlans.length/10)),currentPlanPage=Math.min(planPage,planPages);
 const editable=!id||own(classes.find((c:any)=>c.id===id)||{});
 async function archive(action:string,record:any){if(!window.confirm('삭제할까요? 기존 수업 일지와 성적 기록은 유지됩니다.'))return;await request(action,{id:record.id,revision:record.revision??(action==='archive-class'?classRevision:planRevision)});await refresh();if(action==='archive-class'){setId(null);setClassRevision(0);setForm(blank());}else{setPlanId(null);setPlanRevision(0);setPlan({title:'',subject:'영어',content:'',classId:''});}setNotice('삭제했습니다.');}
 const createClass=()=>{setId(null);setClassRevision(0);setForm(blank());setClassBaseline(JSON.stringify(blank()));setEditorOpen(true);};
 if(createRef)createRef.current=createClass;
 return <div className="space-y-4">{mode==='schedule'&&<section className="panel regular-calendar schedule-regular" hidden={view!=='regular'}><h2 className="sr-only">정규 시간표</h2><p className="schedule-regular-help">매주 반복되는 기본 시간표입니다. 날짜별 변경·보강은 이번 주 일정에 등록하세요.</p><WeekBoard mode="regular" today={koreanDay()} days={weekdays.map(day=>({id:String(day),label:dayNames[day],events:classes.filter((c:any)=>c.status!=='중단').flatMap((c:any)=>(c.slots||[]).filter((s:any)=>s.status!=='중단'&&s.weekday===day).map((slot:any)=>({c,slot}))).sort((a:any,b:any)=>a.slot.start.localeCompare(b.slot.start)||a.slot.end.localeCompare(b.slot.end)||a.c.name.localeCompare(b.c.name))}))} onAdd={createClass} renderEvent={({c,slot})=><ScheduleEventCard variant="regular" time={`${slot.start}–${slot.end}`} title={c.name} subtitle={`${c.students.length}명 · ${c.subject}`} classState={slot.status||c.status||'진행 중'} syncStatus={c.notionSyncStage} onOpen={()=>open(c)}/>}/></section>}
 <div className={mode==='curriculum'?'curriculum-management-board':'grid gap-4'}>{mode==='schedule'?<ScheduleClassCards classes={classes} students={data.students} onOpen={open} selectedId={id} hidden={view!=='classes'}/>:<section hidden={false&&view!=='classes'} className={false?'panel schedule-class-panel':'panel'}><div className="flex flex-wrap justify-between items-center gap-2 mb-3"><h2 className="!mb-0">반 관리 <span className="text-xs font-normal text-slate-400">{classes.length}개</span></h2><button className="small-button" disabled={busy} onClick={()=>{setId(null);setClassRevision(0);setForm(blank());setClassBaseline(JSON.stringify(blank()));setEditorOpen(true);}}>+ 새 반</button></div><div className={false?'schedule-class-cards':''}>{classes.map((c:any)=><button key={c.id} className={false?'schedule-class-card':'block w-full text-left border-b py-3'} aria-pressed={id===c.id} onClick={()=>open(c)}><span className="flex justify-between items-center gap-2"><strong className="text-sm">{c.name}</strong>{false&&<span className="text-xs text-pink-500">수정 ↗</span>}</span><span className="block text-xs text-slate-500 mt-1">{c.status||'진행 중'} · {c.subject} · {c.students.length}명 · 교재 {(c.books||[]).length}권</span>{false&&<span className="block text-xs text-slate-600 mt-3">{(c.slots||[]).length?(c.slots||[]).slice().sort((a:any,b:any)=>weekdays.indexOf(a.weekday)-weekdays.indexOf(b.weekday)||a.start.localeCompare(b.start)).map((slot:any,i:number)=><span key={slot.id||i} className="block">{dayNames[slot.weekday]} {slot.start}–{slot.end} · {slot.status||c.status||'진행 중'}</span>):'정규 시간 미등록'}</span>}</button>)}</div>{!classes.length&&<p className="text-xs text-slate-500">새 반을 등록해 주세요.</p>}</section>}
 {mode==='curriculum'&&<section className="panel"><div className="flex justify-between items-center"><h2>커리큘럼 관리</h2><button className="small-button" disabled={busy} onClick={()=>{setPlanId(null);setPlanRevision(0);setPlan({title:'',subject:form.subject,content:'',classId:''});setPlanEditorOpen(true);}}>+ 커리큘럼·교재 등록</button></div>{visiblePlans.slice((currentPlanPage-1)*10,currentPlanPage*10).map((c:any)=><button className="block text-left w-full py-3 border-b" key={c.id} onClick={()=>{setPlanId(c.id);setPlanRevision(c.revision||0);setPlan({title:c.title,subject:c.subject,content:c.content,classId:c.isCommon?'':c.classId||''});setPlanEditorOpen(true);}}><strong>{c.title}</strong><span className="block text-xs text-slate-500">{(c.classId&&!c.isCommon ? classes.find((r:any)=>r.id===c.classId)?.name||'연결된 반 없음' : '공통 계획')} · {c.subject}</span></button>)}<div className="review-pagination"><button disabled={currentPlanPage===1} onClick={()=>setPlanPage(currentPlanPage-1)}>이전</button><span>{currentPlanPage} / {planPages}</span><button disabled={currentPlanPage===planPages} onClick={()=>setPlanPage(currentPlanPage+1)}>다음</button></div></section>}
 <WorkspaceDialog open={editorOpen&&active} title={id?'반·정규 수업 수정':'반·정규 수업 추가'} onClose={()=>{if(classWorking||JSON.stringify(form)===classBaseline||window.confirm('저장하지 않은 반·시간표 변경을 취소하고 닫을까요?'))setEditorOpen(false);}}><section className="class-editor"><fieldset disabled={busy||!editable}><div className="class-basics"><label>반 이름<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>과목<select value={form.subject} onChange={e=>setForm({...form,subject:e.target.value,students:[]})}>{subjects.map(s=><option key={s}>{s}</option>)}</select></label><label>반 상태<select value={form.status} onChange={e=>setForm({...form,status:e.target.value,slots:e.target.value==='중단'?form.slots.map(s=>({...s,status:'중단'})):form.slots})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label></div><div className="class-students-heading"><strong>학생</strong><span>{form.students.length}명 선택</span></div><div className="lesson-mode-switch class-student-group" role="group" aria-label="반 학생 구분">{[['active','재원생'],['other','이외']].map(([key,label])=><button key={key} type="button" aria-pressed={group===key} onClick={()=>setGroup(key)}>{label}</button>)}</div><input aria-label="반 학생 검색" placeholder="학생 이름 검색" value={search} onChange={e=>setSearch(e.target.value)}/><div className="class-student-chips">{visible.map((student:any)=><button key={student.studentKey} type="button" aria-pressed={form.students.includes(student.studentKey)} onClick={()=>setForm({...form,students:form.students.includes(student.studentKey)?form.students.filter(key=>key!==student.studentKey):[...form.students,student.studentKey]})}>{form.students.includes(student.studentKey)&&<Check size={14}/>} {student.studentDisplayName}</button>)}{!visible.length&&<p>해당 학생이 없습니다.</p>}</div>
 <details open={mode==='schedule'} className="mt-4"><summary className="font-bold text-sm cursor-pointer">정규 수업 요일·시간 ({form.slots.length}개)<OptionalMark/></summary>{form.slots.map((slot,i)=><div className="class-slot-row" key={i}><ChipGroup label="요일" options={weekdays.map(day=>dayNames[day])} value={dayNames[slot.weekday]} onChange={choice=>setForm({...form,slots:form.slots.map((s,j)=>j===i?{...s,weekday:dayNames.indexOf(choice)}:s)})}/>{['start','end'].map(k=><input key={k} aria-label={k==='start'?'정규 시작':'정규 종료'} type="time" value={slot[k]} onChange={e=>setForm({...form,slots:form.slots.map((s,j)=>j===i?{...s,[k]:e.target.value}:s)})}/>)}<select aria-label="정규 시간표 상태" value={slot.status||form.status} onChange={e=>{if(e.target.value==='중단'&&form.status!=='중단'){setStopSlot(i);return;}setForm({...form,slots:form.slots.map((s,j)=>j===i?{...s,status:e.target.value}:s)});}}>{statuses.map(s=><option key={s} disabled={form.status==='중단'&&s!=='중단'}>{s}</option>)}</select><button className="small-button" aria-label="정규 시간 삭제" onClick={()=>setForm({...form,slots:form.slots.filter((_,j)=>i!==j)})}><Trash2 size={16}/></button></div>)}<button className="small-button class-slot-add" onClick={()=>setForm({...form,slots:[...form.slots,{weekday:1,start:'14:00',end:'15:30',status:form.status}]})}>+ 수업 시간</button></details>
 <details open={mode==='curriculum'} className="mt-4"><summary className="font-bold text-sm cursor-pointer">교재 {form.books.length}권 · {form.books.slice(0,2).map(book=>book.title||'새 교재').join(' · ')}{form.books.length>2?' …':''}<OptionalMark/></summary><label className="block mt-3">공통 계획에서 교재 선택<select value="" onChange={e=>{const c=data.curricula.find((c:any)=>c.id===e.target.value);if(!c||form.books.some(b=>b.linkedPlanId===c.id||b.id===(c.notionPageId||c.id)))return;setForm({...form,books:[...form.books,{id:c.notionPageId||c.id,linkedPlanId:c.id,title:c.title,status:'planned',notionEditedAt:c.notionEditedAt}]});}}><option value="">등록된 공통 교재 선택</option>{data.curricula.filter((c:any)=>(!c.classId||c.isCommon)&&c.subject===form.subject&&!c.archived).map((c:any)=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label>{form.books.map((book,i)=><div className="grid grid-cols-[1fr_110px_auto] gap-2 mt-2" key={i}><input aria-label="교재명" readOnly={Boolean(book.linkedPlanId)} value={book.title} onChange={e=>setForm({...form,books:form.books.map((b,j)=>j===i?{...b,title:e.target.value}:b)})}/><select aria-label="교재 사용 상태" disabled={Boolean(book.linkedPlanId)} value={book.status} onChange={e=>setForm({...form,books:form.books.map((b,j)=>j===i?{...b,status:e.target.value}:b)})}><option value="planned">사용 예정</option><option value="current">사용 중</option><option value="past">사용 완료</option></select><button className="small-button" onClick={()=>setForm({...form,books:form.books.filter((_,j)=>i!==j)})}>삭제</button></div>)}<button className="small-button mt-2" onClick={()=>setForm({...form,books:[...form.books,{title:'',status:'planned'}]})}>+ 새 교재</button></details><ScheduleActionBar syncStatus={classWorking?'syncing':classes.find((c:any)=>c.id===id)?.notionSyncStage}><button className="primary-button" disabled={!form.name.trim()} onClick={()=>act(async()=>{setClassWorking(true);try{const r=await request('save-class',{id,revision:classRevision,notionEditedAt:classes.find((c:any)=>c.id===id)?.notionEditedAt,data:form});setId(r.id);setClassRevision(r.revision);setClassBaseline(JSON.stringify(form));await refresh();setNotice(r.syncError ? '앱에 저장됨 · 노션 반영 실패: '+r.syncError : r.sourceMode==='firestore'?'반을 앱에 저장했습니다.':'반을 저장하고 노션에 반영했습니다.');}finally{setClassWorking(false);}})}>저장·반영</button><details className="schedule-danger-menu"><summary aria-label="반 작업" title="반 작업"><MoreHorizontal size={16}/></summary><div>{id&&<button className="small-button schedule-danger-action" onClick={()=>act(()=>archive('archive-class',{id}))}>반 삭제</button>}</div></details></ScheduleActionBar></fieldset>{classWorking&&<p role="status" className="text-sm mt-3">저장·반영 중입니다. 창을 닫아도 요청은 계속 진행됩니다.</p>}{notice&&<p role="status" className="text-sm mt-3">{notice}</p>}{!editable&&<p className="text-xs text-slate-500">담당 선생님의 반입니다. 조회할 수 있습니다.</p>}</section></WorkspaceDialog></div>
{stopSlot!==null&&<WorkspaceDialog open={active} title="해당 반도 중단할까요?" onClose={()=>setStopSlot(null)}><p className="text-sm mb-4">시간표만 중단하거나, 반과 연결된 모든 시간표를 함께 중단할 수 있습니다. 선택 후 반 저장을 눌러 주세요.</p><div className="flex gap-2"><button className="small-button" onClick={()=>{setForm({...form,slots:form.slots.map((s,i)=>i===stopSlot?{...s,status:'중단'}:s)});setStopSlot(null);}}>시간표만 중단</button><button className="primary-button" onClick={()=>{setForm({...form,status:'중단',slots:form.slots.map(s=>({...s,status:'중단'}))});setStopSlot(null);}}>반도 함께 중단</button></div></WorkspaceDialog>}
<WorkspaceDialog open={planEditorOpen&&active} title={planId?'커리큘럼 수정':'커리큘럼·교재 등록'} onClose={()=>{if(!busy)setPlanEditorOpen(false);}}><section className="panel"><h2>커리큘럼 {planId?'수정':'등록'}</h2><fieldset disabled={busy||Boolean(planId&&!own(data.curricula.find((c:any)=>c.id===planId)||{}))}><label>반<OptionalMark/><select value={plan.classId} onChange={e=>{const c=classes.find((c:any)=>c.id===e.target.value);setPlan({...plan,classId:e.target.value,subject:c?.subject||plan.subject});}}><option value="">반 선택 (공통 계획은 선택하지 않아도 됩니다)</option>{classes.filter(own).map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="block mt-3">제목<input value={plan.title} onChange={e=>setPlan({...plan,title:e.target.value})}/></label><label className="block mt-3">과목<select disabled={Boolean(plan.classId)} value={plan.subject} onChange={e=>setPlan({...plan,subject:e.target.value})}>{subjects.map(s=><option key={s}>{s}</option>)}</select></label><label className="block mt-3">진도·수업 계획<OptionalMark/><textarea rows={6} value={plan.content} onChange={e=>setPlan({...plan,content:e.target.value})}/></label><div className="flex gap-2 mt-3"><button className="primary-button" disabled={!plan.title.trim()} onClick={()=>act(async()=>{const r=await request('save-curriculum',{id:planId,revision:planRevision,notionEditedAt:data.curricula.find((c:any)=>c.id===planId)?.notionEditedAt,data:{...plan,classId:plan.classId||null}});setPlanId(r.id);setPlanRevision(r.revision);await refresh();setNotice(r.syncError ? '앱에 저장됨 · 노션 반영 실패: '+r.syncError : '커리큘럼을 저장하고 노션에 반영했습니다.');})}>저장</button>{planId&&<button className="small-button" onClick={()=>act(()=>archive('archive-curriculum',{id:planId}))}>삭제</button>}</div></fieldset>{classWorking&&<p role="status" className="text-sm mt-3">저장·반영 중입니다. 창을 닫아도 요청은 계속 진행됩니다.</p>}{notice&&<p role="status" className="text-sm mt-3">{notice}</p>}<button className="small-button mt-2" onClick={()=>{setPlanId(null);setPlanRevision(0);setPlan({title:'',subject:form.subject,content:'',classId:id||''});}}>새 계획</button></section></WorkspaceDialog>{notice&&<p role="status" className="text-sm text-slate-600">{notice}</p>}</div>;
}

