import {useState} from 'react';
import {Info,BookOpen,CheckCircle2,Trophy,TrendingUp} from 'lucide-react';
import ChipGroup from './ChipGroup';
import ScoreTrend from '../reports/ScoreTrend';
import StatCard from '../reports/StatCard';
import SessionRow from '../reports/SessionRow';
import StatusBadge from './StatusBadge';
import {testPercentage,sessionMatches,filteredActivities,wrongRowExpanded} from '../../lib/teacherReportPresentation';
const filters=[['all','전체'],['test','단어 테스트'],['quiz','퀴즈'],['flashcard','플래시카드'],['grammar','문법'],['exam','시험 대비']];
const modes:Record<string,string>={quiz:'객관식 퀴즈',flashcard:'플래시카드',match:'매치 게임',conjugation:'3단 변화',test:'단어 테스트'};
const date=(v:string|null,options:any={month:'long',day:'numeric',weekday:'short'})=>v?new Date(v).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul',...options}):'날짜 미상';
export default function TeacherOnlineLearning({data,page,onPrevious,onNext,loading}:any){
 const [filter,setFilter]=useState('all'),[wrongOnly,setWrongOnly]=useState(false),[expanded,setExpanded]=useState<string[]>([]);
 if(!data)return <p role="status">온라인 학습 기록을 불러오는 중…</p>;
 const reasons:Record<string,string>={'account-not-linked':'학생 앱 계정이 연결되지 않아 온라인 학습 이력을 조회할 수 없습니다.','account-link-mismatch':'학생 계정 연결을 확인해야 합니다. 다른 계정의 기록은 표시하지 않습니다.','subject-not-available':'온라인 단어·문법 학습 기록은 영어 담당 범위에서 확인할 수 있습니다.'};
 if(data.reason)return <div role="status" className="report-online-empty"><Info size={20}/><p>{reasons[data.reason]||'온라인 기록을 확인할 수 없습니다.'}</p></div>;
 const sessions=data.sessions||[],loadedTests=sessions.filter((s:any)=>s.type==='test').map((s:any)=>({...s,percentage:testPercentage(s.score,s.totalItems)})),tests=loadedTests.filter((s:any)=>s.percentage!==null);
 const latest=[...loadedTests].sort((a:any,b:any)=>Date.parse(b.createdAt)-Date.parse(a.createdAt))[0]?.percentage??null,average=tests.length?Math.round(tests.reduce((sum:number,s:any)=>sum+s.percentage,0)/tests.length*10)/10:null;
 const visible=filteredActivities<any>(sessions,filter,wrongOnly);const labels=filters.map(([key,label])=>`${label} ${sessions.filter((s:any)=>sessionMatches(s,key)).length}`);const wrongIds=visible.filter((s:any)=>s.incorrectCount>0).map((s:any)=>s.id),allOpen=wrongOnly||wrongIds.length>0&&wrongIds.every((id:string)=>expanded.includes(id));
 return <div className="review-section report-online"><div className="report-online-caption"><span>온라인 학습 · 읽기 전용</span><span tabIndex={0} title="완료·오답·포인트 상태는 변경하지 않습니다." aria-label="읽기 전용 안내">ⓘ</span></div>
 <div className="report-stats"><StatCard label="학습 단어 기록" value={<><BookOpen size={16}/>{data.progress?.recorded??'—'}개</>}/><StatCard label="암기 완료" value={<><CheckCircle2 size={16}/>{data.progress?.learned??'—'}개</>}/><StatCard label="최근 단어 테스트" value={<><Trophy size={16}/>{latest===null?'—':`${latest}%`}</>}/><StatCard label="평균" value={<><TrendingUp size={16}/>{average===null?'—':`${average}%`}</>}/></div><p className="report-caption">최근 {loadedTests.length}회 기준</p>
 <ScoreTrend points={[...tests].sort((a:any,b:any)=>Date.parse(a.createdAt)-Date.parse(b.createdAt)).map((s:any)=>({id:s.id,value:s.percentage,date:date(s.createdAt,{month:'numeric',day:'numeric'})}))}/>
 <div className="report-learning-filters"><div className="report-filter-chips"><ChipGroup label="활동 유형" options={labels} value={labels[filters.findIndex(([key])=>key===filter)]} onChange={label=>setFilter(filters[labels.indexOf(label)][0])}/></div><span tabIndex={0} title="건수와 필터는 현재 불러온 페이지 기준입니다." aria-label="현재 페이지 필터 안내">ⓘ</span><label className="report-wrong-toggle"><input type="checkbox" checked={wrongOnly} onChange={e=>setWrongOnly(e.target.checked)}/>오답만 보기</label><button type="button" className="report-expand-all" disabled={!wrongIds.length} onClick={()=>{setWrongOnly(false);setExpanded(allOpen?[]:wrongIds);}}>{allOpen?'모두 접기':'모두 펼치기'}</button></div>
 {!visible.length&&<p className="report-caption">{!sessions.length?'저장된 온라인 학습 활동이 없습니다.':'이 필터에 해당하는 활동이 없습니다.'}</p>}
 {visible.map((s:any,index:number)=>{const percentage=testPercentage(s.score,s.totalItems),seconds=typeof s.duration==='number'?Math.max(0,Math.round(s.duration)):null,open=wrongRowExpanded(s.id,wrongOnly,expanded),day=date(s.createdAt);return <div key={s.id}>{(index===0||day!==date(visible[index-1].createdAt))&&<h4 className="report-activity-date">{day}</h4>}<SessionRow test={s.type==='test'} title={s.wordbookTitle} range={s.dayStart==null?'':s.dayStart===s.dayEnd?`Day ${s.dayStart}`:`범위 ${s.dayStart}${s.dayEnd==null?'':'–'+s.dayEnd}`} meta={`${modes[s.type]||s.type||'학습'} · ${s.category==='grammar'?'문법':s.category==='exam'?'시험 대비':'단어'} · ${s.createdAt?new Date(s.createdAt).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit'}):'—'}`} score={<div className="report-inline-score text-emerald-600"><strong><span className="sr-only">정답 </span>{s.score??'—'}/{s.totalItems??'—'} · {percentage===null?'—':`${percentage}%`}</strong>{percentage!==null&&<progress max={100} value={percentage} aria-label="학습 점수"/>}<small>{seconds===null?'—':`${Math.floor(seconds/60)}분 ${seconds%60}초`}</small></div>} action={s.incorrectCount>0?<button type="button" className="report-wrong-button" aria-expanded={open} aria-controls={`wrong-${s.id}`} onClick={()=>{if(wrongOnly){setWrongOnly(false);setExpanded(wrongIds.filter((id:string)=>id!==s.id));}else setExpanded(old=>open?old.filter(id=>id!==s.id):[...old,s.id]);}}>오답 {s.incorrectCount} {open?'▴':'▾'}</button>:<span className="report-no-wrong">오답 없음</span>}>
 {open&&s.incorrectCount>0&&<div id={`wrong-${s.id}`} className="report-wrong-grid">{(s.incorrectAnswers||[]).map((a:any,i:number)=><div key={i}><strong>{a.word}</strong> <span>{a.meaning}</span>{a.quizSentence&&<p>{a.quizSentence}</p>}<p><span className="report-answer status-danger">선택한 답: {a.userChoice||'미선택'}</span> → <span className="report-answer status-success">정답: {a.correctAnswer}</span></p><small>{a.isReviewed?'복습 확인됨':'복습 미확인'}</small></div>)}{s.incorrectCount>(s.incorrectAnswers?.length||0)&&<p>오답이 많아 앞 {s.incorrectAnswers?.length||0}개를 표시합니다.</p>}</div>}
 </SessionRow></div>;})}
 <div className="review-pagination"><button type="button" disabled={loading||page===0} onClick={onPrevious}>이전</button><span>{page+1}페이지</span><button type="button" disabled={loading||!data.nextCursor} onClick={onNext}>다음</button></div>
 <section className="report-online-assignments"><h4>앱 과제 · 최근 10개</h4>{(data.assignments||[]).map((a:any)=><article key={a.id} className="report-assignment"><p>{date(a.createdAt)} <StatusBadge kind={a.isDone?'done':'saved'} text={a.isDone?'완료':'미완료'}/></p><p>{a.content}</p></article>)}{!data.assignments?.length&&<p className="report-caption">앱 과제가 없습니다. 수업 일지 과제는 수업 기록에서 확인할 수 있습니다.</p>}</section>
 </div>;
}
