import WorkspaceDialog from './WorkspaceDialog';
import {examPeriod} from '../../lib/academicExamPeriod';
import {useEffect,useState} from 'react';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(new Date());
const blank=()=>({examYear:new Date().getFullYear(),semester:1,examPeriod:'중간고사',studentKey:'',subject:'영어',examType:'학교 내신',title:'',examDate:today(),deadline:null as string|null,score:null as number|null,maxScore:100 as number|null,grade:'',submissionStatus:'제출 완료',note:''});
export default function TeacherAcademicManager({data,busy,request,act}:{data:any;busy:boolean;request:(action?:string,body?:any)=>Promise<any>;act:(f:()=>Promise<any>)=>Promise<void>}) {
 const [records,setRecords]=useState<any[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState('');
 const [value,setValue]=useState<any>(()=>({...blank(),subject:data.scopes?.[0]?.subject||'영어'})),[selected,setSelected]=useState<any>(null),[saved,setSaved]=useState<any>(null);
 const [teacher,setTeacher]=useState(''),[student,setStudent]=useState(''),[kind,setKind]=useState('학교 내신'),[subject,setSubject]=useState(''),[page,setPage]=useState(1);
 const [dialog,setDialog]=useState(false),[search,setSearch]=useState(''),[period,setPeriod]=useState('');
 const editable=canEdit(selected);
 function canEdit(r:any){return !r||(!r.readOnly&&(data.admin||r.ownerUid===data.uid||r.source==='notion'));}
 async function load(){const result=await request('read:academic-records');setRecords(result.records);setLoaded(true);setError('');return result.records;}
 useEffect(()=>{let live=true; request('read:academic-records').then(r=>{if(live){setRecords(r.records);setLoaded(true);}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[]);
 function field(key:string,v:any){setValue((old:any)=>({...old,[key]:v}));}
 const visible=records.filter(r=>(!teacher||r.ownerUid===teacher||r.teacherUids?.includes(teacher))&&(!student||r.data.studentKey===student)&&(!kind||r.data.examType===kind)&&(!subject||r.data.subject===subject)&&(!period||examPeriod(r.data)?.key===period)&&(!search||[r.data.title,r.data.subject,r.data.note,data.students.find((x:any)=>x.studentKey===r.data.studentKey)?.studentDisplayName].join(' ').toLowerCase().includes(search.toLowerCase()))).sort((a,b)=>b.data.examDate.localeCompare(a.data.examDate));
 const pages=Math.max(1,Math.ceil(visible.length/10)),current=Math.min(page,pages);
 const writableStudents=data.students.filter((s:any)=>data.admin||(data.principal?data.teachingScopes||[]:data.scopes).some((scope:any)=>scope.studentKey===s.studentKey));
 const canWrite=!data.principal||writableStudents.length>0;
 const changed=JSON.stringify(saved)!==JSON.stringify(value);
 return <div>
 <WorkspaceDialog open={dialog} title={selected?'성적 수정':'성적 입력'} onClose={()=>{if(!busy)setDialog(false);}}><section className="panel"><h2>성적 입력</h2><fieldset disabled={busy||!canWrite||!editable}>
 <div className="grid grid-cols-2 gap-2"><label>학생<select value={value.studentKey} onChange={e=>field('studentKey',e.target.value)}><option value="">학생 선택</option>{writableStudents.map((s:any)=><option key={s.studentKey} value={s.studentKey}>{s.studentDisplayName}</option>)}</select></label><label>과목<select value={value.subject} onChange={e=>field('subject',e.target.value)}>{['영어','수학','국어','과학','한국사'].filter(subject=>data.admin||(data.principal?data.teachingScopes||[]:data.scopes).some((s:any)=>s.subject===subject&&(!value.studentKey||s.studentKey===value.studentKey))).map(s=><option key={s}>{s}</option>)}</select></label>
 <label>구분<select value={value.examType} onChange={e=>field('examType',e.target.value)}><option>학교 내신</option><option>학력평가</option></select></label><label>시험일<input type="date" required value={value.examDate} onChange={e=>field('examDate',e.target.value)}/></label></div>
 {value.examType==='학교 내신'&&<div className="grid grid-cols-3 gap-2 mt-2"><label>연도<input type="number" min="1900" max="2200" value={value.examYear??''} onChange={e=>field('examYear',e.target.value?Number(e.target.value):null)}/></label><label>학기<select value={value.semester??''} onChange={e=>field('semester',e.target.value?Number(e.target.value):null)}><option value="">미분류</option><option value="1">1학기</option><option value="2">2학기</option></select></label><label>고사<select value={value.examPeriod??''} onChange={e=>field('examPeriod',e.target.value||null)}><option value="">미분류</option><option>중간고사</option><option>기말고사</option></select></label></div>}
 <label className="block mt-2">시험명<input value={value.title} onChange={e=>field('title',e.target.value)} placeholder="예: 2학기 중간고사"/></label>
 <div className="grid grid-cols-2 gap-2 mt-2"><label>제출 상태<select value={value.submissionStatus} onChange={e=>setValue((v:any)=>({...v,submissionStatus:e.target.value,score:e.target.value==='제출 완료'?v.score:null}))}><option>제출 완료</option><option>미제출</option><option>제출 대상 아님</option></select></label><label>예상 등급<input value={value.grade} onChange={e=>field('grade',e.target.value)} placeholder="숫자 또는 A/B"/></label>{[['score','원점수'],['maxScore','만점']].map(([key,label])=><label key={key}>{label}<input type="number" step="any" min={key==='score'?0:0.01} disabled={key==='score'&&value.submissionStatus!=='제출 완료'} value={value[key]??''} onChange={e=>field(key,e.target.value===''?null:Number(e.target.value))}/></label>)}
 <label>제출 기한 · 선택<input type="date" value={value.deadline||''} onChange={e=>field('deadline',e.target.value||null)}/></label></div>
 <label className="block mt-2">비고<textarea rows={2} value={value.note} onChange={e=>field('note',e.target.value)}/></label>
 <div className="flex flex-wrap gap-2 mt-3"><button className="primary-button" onClick={()=>act(async()=>{const result=await request('save-academic',{id:selected?.id,revision:selected?.revision,notionPageId:selected?.source==='notion'?selected.notionPageId:undefined,data:value});const fresh=await load();const record=fresh.find((r:any)=>r.id===result.id);setSelected(record);setSaved(record.data);setValue(record.data);})}>저장</button><button className="small-button" disabled={!selected?.revision||changed||['published','publishing','notion_saved'].includes(selected?.stage)} onClick={()=>act(async()=>{await request('publish-academic',{id:selected.id});const fresh=await load();setSelected(fresh.find((r:any)=>r.id===selected.id));})}>반영</button><button className="small-button" onClick={()=>{setSelected(null);setSaved(null);setValue(blank());}}>새 성적</button></div>
 <p className="text-xs text-slate-500 mt-2">저장은 초안 보관, 반영은 Notion과 학생·학부모 성적에 적용합니다.</p>{selected&&<p role="status" className="text-xs text-slate-500 mt-2">{({draft:'저장됨',published:'반영 완료',failed:'반영 실패',notion_saved:'Notion 저장됨',publishing:'반영 중'} as any)[selected.stage]}</p>}
 </fieldset></section></WorkspaceDialog>
 <section className="panel"><div className="flex justify-between gap-2"><h2>성적 기록 · {visible.length}건</h2><div className="flex flex-wrap gap-2 items-center">{['학교 내신','학력평가'].map(k=><button key={k} className={kind===k?'primary-button':'small-button'} aria-pressed={kind===k} onClick={()=>{setKind(k);setPage(1);setPeriod('');}}>{k==='학교 내신'?'내신':k}</button>)}<button className="small-button" disabled={busy} onClick={()=>act(load)}>새로고침</button>{canWrite&&<button className="primary-button" disabled={busy} onClick={()=>{setSelected(null);setSaved(null);setValue({...blank(),examType:kind,subject:data.scopes?.[0]?.subject||'영어'});setDialog(true);}}>+ 성적 입력</button>}</div></div>
 <div className="workspace-filters mb-3">{(data.admin||data.principal)&&<label>담당 선생님<select aria-label="성적 선생님 필터" value={teacher} onChange={e=>{setTeacher(e.target.value);setPage(1);}}><option value="">전체 선생님</option>{[...new Set(records.flatMap(r=>r.teacherUids?.length?r.teacherUids:[r.ownerUid]).filter(Boolean))].map(uid=><option key={uid} value={uid}>{data.staff?.find((s:any)=>s.uid===uid)?.name || (uid===data.uid?'나':'연결되지 않은 작성자')}</option>)}</select></label>}<label>학생<select aria-label="학생 필터" value={student} onChange={e=>{setStudent(e.target.value);setPage(1);}}><option value="">전체 학생</option>{data.students.map((s:any)=><option key={s.studentKey} value={s.studentKey}>{s.studentDisplayName}</option>)}</select></label>{kind==='학교 내신'&&<label>학기·고사<select value={period} onChange={e=>{setPeriod(e.target.value);setPage(1);}}><option value="">전체 학기·고사</option>{Array.from(new Map<string,NonNullable<ReturnType<typeof examPeriod>>>(records.map(r=>examPeriod(r.data)).filter(Boolean).map(p=>[p!.key,p!])).values()).sort((a,b)=>b.key.localeCompare(a.key)).map(p=><option key={p.key} value={p.key}>{p.label}</option>)}</select></label>}<label>검색<input type="search" placeholder="학생·시험명·과목 검색" value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></label><label>과목<select aria-label="과목 필터" value={subject} onChange={e=>{setSubject(e.target.value);setPage(1);}}><option value="">전체 과목</option>{['영어','수학','국어','과학','한국사'].map(s=><option key={s}>{s}</option>)}</select></label></div>
 {error&&<p role="alert" className="text-sm text-rose-600">{error}</p>}{!loaded&&!error&&<p className="text-sm text-slate-500">성적을 불러오는 중…</p>}
 <div className="academic-cards">{visible.slice((current-1)*10,current*10).map(r=><button key={r.id} type="button" className="academic-card" aria-label={`${data.students.find((s:any)=>s.studentKey===r.data.studentKey)?.studentDisplayName||'학생'} ${r.data.title} 성적 보기`} onClick={()=>{const p=examPeriod(r.data);const v={...r.data,examYear:p?.year??r.data.examYear??(Number(r.data.examDate?.slice(0,4))||null),semester:p?.semester??r.data.semester??null,examPeriod:p?.period??r.data.examPeriod??null};setSelected(r);setSaved(r.source==='notion'?null:v);setValue(v);setDialog(true);}}><strong>{data.students.find((s:any)=>s.studentKey===r.data.studentKey)?.studentDisplayName||'학생'} · {r.data.title}</strong><span className="text-xl font-bold text-pink-600">{r.data.submissionStatus==='제출 완료'&&r.data.score!==null?`${r.data.score} / ${r.data.maxScore??'—'}`:r.data.submissionStatus}</span><span className="text-xs text-slate-500">{examPeriod(r.data)?.label||r.data.examType} · {r.data.examDate} · {r.data.subject}{r.data.grade?` · 등급 ${r.data.grade}`:''}</span><span className="text-xs text-slate-500">{r.stage==='published'?'반영 완료':r.stage==='draft'?'저장됨':r.stage==='failed'?'반영 실패':'반영 중'} · {canEdit(r)&&canWrite?'클릭하여 수정':'클릭하여 보기'}</span></button>)}</div>
 {loaded&&!visible.length&&<p className="text-sm text-slate-500 py-3">해당하는 성적이 없습니다.</p>}<div className="review-pagination"><button disabled={current===1} onClick={()=>setPage(current-1)}>이전</button><span>{current} / {pages}</span><button disabled={current===pages} onClick={()=>setPage(current+1)}>다음</button></div></section>
 </div>;
}
