import { useState } from 'react';
import { applyCommonLesson, gridCanPublish, gridScore, newGridLesson, processLessonRows } from '../../lib/teacherLessonGrid';
interface Props {
    data: any;
    busy: boolean;
    request: (action?: string, body?: any) => Promise<any>;
    refresh: () => Promise<void>;
    act: (callback: () => Promise<any>) => Promise<void>;
}
interface Row {
    id: string;
    revision?: number;
    stage: string;
    data: ReturnType<typeof newGridLesson>;
    savedData?: any;
    error?: string;
}
const evaluations = ['미확인', '미제출', '최하', '하', '중하', '중', '중상', '상', '최상'];
export default function TeacherLessonGrid({ data, busy, request, refresh, act }: Props) {
    const [rows, setRows] = useState<Row[]>([]), [selection, setSelection] = useState<string[]>([]), [checked, setChecked] = useState<string[]>([]);
    const [subject, setSubject] = useState(data.scopes?.[0]?.subject || '영어'), [date, setDate] = useState(() => new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Seoul' }).format(new Date())), [start, setStart] = useState('14:00'), [end, setEnd] = useState('15:30');
    const [common, setCommon] = useState({ content: '', assignment: '', nextPlan: '' }), [notice, setNotice] = useState(''), [search, setSearch] = useState('');
    const students = data.students.filter((s: any) => data.admin || data.scopes.some((x: any) => x.studentKey === s.studentKey && x.subject === subject));
    const setRow = (id: string, patch: Partial<Row>) => setRows(previous => previous.map(r => r.id === id ? { ...r, ...patch } : r));
    const setField = (id: string, key: string, value: any) => setRows(previous => previous.map(r => r.id === id ? { ...r, error: undefined, data: { ...r.data, [key]: value } } : r));
    async function run(mode: 'save' | 'publish', ids: string[]) {
        const chosen = rows.filter(r => ids.includes(r.id));
        const { succeeded, failed } = await processLessonRows(chosen, mode, request, setRow);
        setNotice(`${mode === 'save' ? '저장' : '반영 요청'} ${succeeded}건${failed ? ` · 실패 ${failed}건 — 해당 학생의 안내를 확인해 주세요.` : ''}`);
        await refresh();
    }
    function addStudents() {
        const added = selection.filter(key => !rows.some(r => r.data.studentKey === key && r.data.subject === subject && r.data.date === date));
        const next = added.map(key => ({ id: crypto.randomUUID(), stage: 'new', data: newGridLesson(key, subject, date, start, end) }));
        setRows(previous => [...previous, ...next]);
        setChecked(previous => [...previous, ...next.map(r => r.id)]);
        setSelection([]);
    }
    return <section className="panel lesson-grid"><div className="flex flex-wrap justify-between gap-2 mb-3"><h2 className="!mb-0">여러 학생 함께 작성</h2><span className="text-xs text-slate-500">학생마다 별도 기록으로 저장됩니다. 탭을 바꿔도 입력은 유지됩니다.</span></div><fieldset disabled={busy}>
 <div className="grid grid-cols-2 sm:grid-cols-4 gap-2"><label>과목<select value={subject} onChange={e => { setSubject(e.target.value); setSelection([]); }}>{['영어', '수학', '국어', '과학', '한국사'].map(s => <option key={s}>{s}</option>)}</select></label><label>날짜<input type="date" value={date} onChange={e => setDate(e.target.value)}/></label><label>시작<input type="time" value={start} onChange={e => setStart(e.target.value)}/></label><label>종료<input type="time" value={end} onChange={e => setEnd(e.target.value)}/></label></div>
 <details className="mt-3 rounded-xl border border-pink-100 p-3"><summary className="text-sm font-bold cursor-pointer">학생 추가 · {selection.length}명 선택</summary><input aria-label="추가할 학생 검색" placeholder="학생 이름 검색" value={search} onChange={e => setSearch(e.target.value)}/><div className="flex flex-wrap gap-x-4 gap-y-1 max-h-40 overflow-auto mt-2">{students.filter((s: any) => s.studentDisplayName.includes(search.trim())).map((s: any) => <label key={s.studentKey} className="flex items-center gap-2 min-h-[36px]"><input type="checkbox" checked={selection.includes(s.studentKey)} onChange={e => setSelection(e.target.checked ? [...selection, s.studentKey] : selection.filter(x => x !== s.studentKey))}/>{s.studentDisplayName}</label>)}</div><button className="small-button mt-2" disabled={!selection.length} onClick={addStudents}>선택한 학생 추가</button></details>
 <details className="mt-3 rounded-xl border border-pink-100 p-3"><summary className="text-sm font-bold cursor-pointer">공통 수업 내용·과제 입력</summary><div className="grid md:grid-cols-3 gap-2 mt-2">{([['content', '수업 내용'], ['assignment', '과제'], ['nextPlan', '다음 수업 메모']] as const).map(([key, label]) => <label key={key}>{label}<textarea rows={2} value={common[key]} onChange={e => setCommon(c => ({ ...c, [key]: e.target.value }))}/></label>)}</div><button className="small-button mt-2" disabled={!checked.length} onClick={() => { if (rows.some(r => checked.includes(r.id) && (r.data.content || r.data.assignment || r.data.nextPlan)) && !window.confirm('선택한 학생의 수업 내용·과제·다음 메모를 공통 입력 내용으로 바꿀까요?'))
        return; setRows(previous => previous.map(r => checked.includes(r.id) ? { ...r, data: applyCommonLesson(r.data, common) } : r)); }}>선택한 {checked.length}명에게 적용</button><button className="small-button ml-2 mt-2" disabled={!checked.length} onClick={() => setRows(previous => previous.map(r => checked.includes(r.id) ? { ...r, data: { ...r.data, attendance: '출석', attitude: '상', homework: '상' } } : r))}>선택한 학생 출석·태도 상·숙제 상</button></details>
 <div className="flex flex-wrap items-center gap-2 my-3"><label className="flex items-center gap-2"><input type="checkbox" checked={rows.length > 0 && checked.length === rows.length} onChange={e => setChecked(e.target.checked ? rows.map(r => r.id) : [])}/>전체 선택</label><button className="primary-button" disabled={!checked.length} onClick={() => act(() => run('save', checked))}>선택 저장</button><button className="small-button" disabled={!checked.length || rows.filter(r => checked.includes(r.id)).some(r => !gridCanPublish(r))} onClick={() => act(async () => { if (window.confirm(`저장한 ${checked.length}명의 기록을 반영할까요?`))
        await run('publish', checked); })}>선택 반영</button><button className="small-button" onClick={() => act(async () => { const fresh = await request(); setRows(previous => previous.map(row => { const saved = fresh.drafts.find((d: any) => d.id === row.id); return saved ? { ...row, revision: saved.revision, stage: saved.stage, savedData: saved.data } : row; })); await refresh(); })}>반영 상태 확인</button></div>
 {notice && <p role="status" className="text-xs text-slate-500 mb-3">{notice}</p>}
 <div className="lesson-grid-scroll" tabIndex={0} aria-label="학생별 수업 입력 표"><table><thead><tr><th>학생</th><th>출결·평가</th><th>점수·회차</th><th>수업 내용·과제</th><th>개인 메모</th><th>저장·반영</th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><label className="flex gap-2 items-center"><input type="checkbox" checked={checked.includes(row.id)} onChange={e => setChecked(e.target.checked ? [...checked, row.id] : checked.filter(x => x !== row.id))}/><strong>{data.students.find((s: any) => s.studentKey === row.data.studentKey)?.studentDisplayName}</strong></label><span className="block text-xs text-slate-500 mt-1">{row.data.subject}</span><input aria-label="수업 날짜" type="date" value={row.data.date} onChange={e => setField(row.id, 'date', e.target.value)}/><div className="flex gap-1">{(['start', 'end'] as const).map(key => <input key={key} aria-label={key === 'start' ? '시작' : '종료'} type="time" value={row.data[key]} onChange={e => setField(row.id, key, e.target.value)}/>)}</div></td><td>{([['attendance', '출결', ['미확인', '출석', '결석', '지각', '보강 출석', '보강 결석', '보강 지각']], ['attitude', '태도', ['미확인', '미참여', '하', '중하', '중', '중상', '상', '최상']], ['homework', '숙제', evaluations], ['test', '테스트', evaluations]] as const).map(([key, label, values]) => <label key={key} className="block mb-1">{label}<select value={row.data[key]} onChange={e => setField(row.id, key, e.target.value)}>{values.map(v => <option key={v}>{v}</option>)}</select></label>)}</td><td>{([['correct', '정답'], ['total', '만점'], ['round', '회차']] as const).map(([key, label]) => <label key={key} className="block mb-1">{label}<input type="number" min={key === 'correct' ? 0 : 1} value={row.data[key] ?? ''} onChange={e => setField(row.id, key, e.target.value === '' ? null : Number(e.target.value))}/></label>)}<p className="text-pink-600 text-xs">환산 {gridScore(row.data.correct, row.data.total) ?? '—'}점</p></td><td><label>수업 내용<textarea rows={3} value={row.data.content} onChange={e => setField(row.id, 'content', e.target.value)}/></label><label className="block mt-1">과제<textarea rows={2} value={row.data.assignment} onChange={e => setField(row.id, 'assignment', e.target.value)}/></label></td><td><label>개인 피드백<textarea rows={3} value={row.data.note} onChange={e => setField(row.id, 'note', e.target.value)}/></label><label className="block mt-1">다음 수업<textarea rows={2} value={row.data.nextPlan} onChange={e => setField(row.id, 'nextPlan', e.target.value)}/></label></td><td><div className="flex flex-col gap-2"><button className="primary-button" onClick={() => act(() => run('save', [row.id]))}>저장</button><button className="small-button" disabled={!gridCanPublish(row)} onClick={() => act(() => run('publish', [row.id]))}>반영</button><button className="small-button" disabled={!row.data.studentKey} onClick={() => act(async () => { const result = await request('previous-lesson', { studentKey: row.data.studentKey, subject: row.data.subject }); if (window.confirm('지난 수업 내용·과제로 이어갈까요? 이번 출결·점수·평가는 초기화됩니다.'))
        setRows(previous => previous.map(r => r.id === row.id ? { ...r, data: { ...r.data, ...result.data } } : r)); })}>이어가기</button><span className="text-xs text-slate-500">{({ new: '작성 중', draft: '저장됨', published: '반영 완료', processing: '반영 중', publishing: '반영 준비 중', failed: '반영 실패' } as Record<string, string>)[row.stage] || row.stage}{row.savedData && JSON.stringify(row.savedData) !== JSON.stringify(row.data) ? ' · 수정됨' : ''}</span>{row.error && <p role="alert" className="text-xs text-rose-600">{row.error}</p>}</div></td></tr>)}</tbody></table>{!rows.length && <p className="text-sm text-slate-500 p-4">학생을 추가하면 여러 명의 수업을 함께 작성할 수 있습니다.</p>}</div>
 </fieldset></section>;
}
