import {useEffect,useId,useRef,useState,type ReactNode} from 'react';
import {Plus} from 'lucide-react';
import {adjacentWeekDay,initialWeekSelection,type WeekColumn} from '../../lib/schedulePresentation';
export default function WeekBoard({days,mode,today,renderEvent,onAdd,loading=false,onSelect,preferredDay}:{days:readonly WeekColumn[];mode:'dated'|'regular';today:string;renderEvent:(event:any,narrow:boolean)=>ReactNode;onAdd:(day:WeekColumn)=>void;loading?:boolean;onSelect?:(id:string)=>void;preferredDay?:string}){
 const id=useId(),strip=useRef<HTMLDivElement>(null),signature=days.map(day=>day.id).join('|');
 const [selected,setSelected]=useState(()=>initialWeekSelection(days,today,mode));
 useEffect(()=>{if(!days.some(day=>day.id===selected))setSelected(initialWeekSelection(days,today,mode));},[signature,today,mode,selected]);
 useEffect(()=>{if(preferredDay&&days.some(day=>day.id===preferredDay))setSelected(preferredDay);},[preferredDay,signature]);
 const isToday=(day:WeekColumn)=>mode==='dated'?day.date===today:day.id===String(new Date(`${today}T00:00:00Z`).getUTCDay());
 const active=days.find(day=>day.id===selected)||days[0];
 const choose=(key:string)=>{setSelected(key);onSelect?.(key);};
 const body=(day:WeekColumn,narrow:boolean)=>loading&&!day.events.length?<div role="status" aria-label="일정을 불러오는 중" className="schedule-skeleton">{[0,1,2].map(i=><span key={i}/>)}</div>:day.events.length?day.events.map((event,index)=><div key={event.id||index}>{renderEvent(event,narrow)}</div>):<div className="schedule-empty-day"><span>일정 없음</span><button type="button" aria-label={`${day.label} ${day.date||''} 일정 추가`} onClick={()=>onAdd(day)}><Plus size={16}/></button></div>;
 return <div className="schedule-week-board" data-mode={mode}><div className="schedule-board-wide">{days.map(day=><section key={day.id} className={`schedule-week-column${(mode==='dated'?day.date===today:day.id===String(new Date(`${today}T00:00:00Z`).getUTCDay()))?' is-today':''}`}><header><strong>{day.label}</strong>{mode==='dated'&&<span>{day.date?.slice(5).replace('-','/')}</span>}<span className="schedule-day-count">{day.events.length}</span><button type="button" aria-label={`${day.label} ${day.date||''} 일정 추가`} onClick={()=>onAdd(day)}><Plus size={16}/></button></header><div className="schedule-day-events">{body(day,false)}</div></section>)}</div><div className="schedule-board-narrow"><div className="schedule-week-strip" role="tablist" aria-label={mode==='dated'?'주간 날짜 선택':'정규 요일 선택'} ref={strip}>{days.map(day=><button type="button" key={day.id} role="tab" data-day={day.id} aria-selected={day.id===active?.id} tabIndex={day.id===active?.id?0:-1} aria-controls={`${id}-agenda`} className={isToday(day)?'is-today':''} onClick={()=>choose(day.id)} onKeyDown={event=>{const next=adjacentWeekDay(days,day.id,event.key);if(next){event.preventDefault();choose(next);strip.current?.querySelector<HTMLButtonElement>(`[data-day="${next}"]`)?.focus();}}}><strong>{day.label}</strong>{mode==='dated'&&<span>{day.date?.slice(5).replace('-','/')}</span>}<span>{day.events.length}건</span></button>)}</div>{active&&<section className="schedule-agenda" id={`${id}-agenda`} role="tabpanel"><header><h3>{mode==='dated'?`${active.date?.slice(5).replace('-','/')}(${active.label})`:active.label} · {active.events.length}건</h3><button type="button" className="small-button" onClick={()=>onAdd(active)}><Plus size={14}/>일정 추가</button></header>{body(active,true)}</section>}</div></div>;
}
